Repository chakra-ui/chakra-ui, pull requests merged in 2020-08, with the labels that each got.

#1314 feat: added storageManager prop to ColorModeProvider
  examples/next-js/pages/_app.js
  examples/next-js/pages/_document.js
  packages/color-mode/src/color-mode.tsx
  packages/color-mode/src/color-mode.utils.ts
  packages/color-mode/src/index.ts
  packages/color-mode/src/storage-manager.ts
  packages/color-mode/src/use-color-mode-state.ts
  packages/system/src/providers.tsx
  website/docs/color-mode.mdx
Labels: Topic: Color Mode 🌓, Topic: Component API ⚙️

#1508 docs(button): remove mention of scale for colorScheme prop
  website/docs/form/button.mdx
Labels: Topic: Documentation 📚

#1514 docs(menu): remove submenu from menu docs
  packages/menu/README.md
  packages/menu/migration.md
  packages/menu/src/menu.tsx
  website/docs/components/menu.mdx
  website/docs/migration.mdx
Labels: Topic: Documentation 📚

#1512 fix(radio): set default isChecked prop value
  packages/radio/src/radio.tsx
  packages/radio/stories/radio.stories.tsx
Labels: Type: Bug 🐛

#1500 style(input-element): remove z-index
  packages/input/src/input-element.tsx
Labels: Topic: Design and UX ✍️

#1467 fix(media-query): create media queries using breakpoint name keys only
  packages/media-query/package.json
  packages/media-query/src/create-media-query.ts
  packages/media-query/tests/create-media-query.test.ts
  packages/media-query/tests/test-data.ts
  packages/media-query/tests/use-breakpoint-value.test.tsx
  yarn.lock
Labels: Topic: Responsive 📱, Type: Bug 🐛

#1398 feat(system): extend props
  packages/system/package.json
  packages/system/src/providers.tsx
Labels: Topic: Component API ⚙️

#1525 docs: theme grammar
  website/pages/docs/theming/theme.mdx
Labels: Topic: Documentation 📚

#1431 chore(system): remove shouldForwardProp isValid check
  packages/system/src/should-forward-prop.ts
  packages/system/tests/should-forward-prop.test.ts
Labels: Topic: Testing 🧪, Type: Bug 🐛

#1565 Docs/chakra provider props
  .storybook/preview.tsx
  examples/create-react-app/src/index.tsx
  examples/next-js/pages/_app.js
  examples/nextjs-typescript/pages/_app.tsx
  tooling/cra-template-typescript/template/src/App.tsx
  tooling/cra-template-typescript/template/src/test-utils.tsx
  tooling/cra-template/template/src/App.js
  tooling/cra-template/template/src/test-utils.js
  website/pages/_app.tsx
  website/pages/docs/features/color-mode.mdx
  website/pages/docs/getting-started.mdx
  website/pages/docs/migration.mdx
  website/pages/docs/principles.mdx
  website/src/components/pagination.tsx
Labels: Topic: Documentation 📚

#1594 fix(checkbox): omit checkbox props from Icon spread
  packages/checkbox/src/checkbox.icon.tsx
Labels: Type: Bug 🐛

#1577 chore(website): fix 'git log' error and add --follow flag
  website/next.config.js
Labels: Topic: Website 🖥

#1576 docs(installation): add CRA templates guide note
  website/pages/docs/getting-started.mdx
Labels: Topic: Documentation 📚

#1578 feat(docs): add Chakra exports as mdx shortcodes
  website/pages/_app.tsx
Labels: Topic: Documentation 📚

#1627 perf: widen As prop typing
  packages/system/src/forward-ref.tsx
Labels: Topic: Performance, Topic: TypeScript 🤠

#1662 docs: added not about RadioButtonGroup being deprecated
  website/pages/docs/migration.mdx
Labels: Topic: Documentation 📚

#1656 Performance: Add isLazy property to Tabs
  packages/tabs/src/use-tabs.ts
  packages/tabs/tests/tabs.test.tsx
  website/pages/docs/components/tabs.mdx
Labels: Topic: Component API ⚙️

#1689 docs: called out that default chakra icons need to be imported from @chakra-ui/icons
  website/pages/docs/components/icon.mdx
Labels: Topic: Documentation 📚

#1688 docs: updated transition section for modal and alert dialog
  website/pages/docs/overlay/alert-dialog.mdx
  website/pages/docs/overlay/modal.mdx
Labels: Topic: Documentation 📚

#1726 fix(modal): fix ModalFooter to use the forwardRef utility
  packages/modal/src/modal.tsx
Labels: Topic: Component API ⚙️

#1722 Feat/extend create icon
  packages/icon/src/create-icon.tsx
  packages/icon/tests/__snapshots__/create-icon.test.tsx.snap
  packages/icon/tests/create-icon.test.tsx
Labels: Topic: Component API ⚙️

#1631 refactor: styleConfigs' internalization
  CONTRIBUTING.md
  README.md
  package.json
  packages/core/src/chakra-provider.tsx
  packages/theme-tools/src/style-config/index.ts
  packages/theme-tools/src/style-config/utils.ts
  packages/theme/src/components/accordion.ts
  packages/theme/src/components/alert.ts
  packages/theme/src/components/avatar.ts
  packages/theme/src/components/badge.ts
  packages/theme/src/components/breadcrumb.ts
  packages/theme/src/components/button.ts
  packages/theme/src/components/checkbox.ts
  packages/theme/src/components/close-button.ts
  packages/theme/src/components/code.ts
  packages/theme/src/components/drawer.ts
  packages/theme/src/components/editable.ts
  packages/theme/src/components/form-label.ts
  packages/theme/src/components/form.ts
  packages/theme/src/components/heading.ts
  packages/theme/src/components/index.ts
  packages/theme/src/components/input.ts
  packages/theme/src/components/kbd.ts
  packages/theme/src/components/link.ts
  packages/theme/src/components/menu.ts
  packages/theme/src/components/modal.ts
  packages/theme/src/components/number-input.ts
  packages/theme/src/components/pin-input.ts
  packages/theme/src/components/popover.ts
  packages/theme/src/components/progress.ts
  packages/theme/src/components/radio.ts
  packages/theme/src/components/select.ts
  packages/theme/src/components/skeleton.ts
  packages/theme/src/components/skip-link.ts
  packages/theme/src/components/slider.ts
  packages/theme/src/components/spinner.ts
  packages/theme/src/components/stat.ts
  packages/theme/src/components/switch.ts
  packages/theme/src/components/tabs.ts
  packages/theme/src/components/tag.ts
  packages/theme/src/components/textarea.ts
  packages/theme/src/components/tooltip.ts
  website/configs/docs-sidebar.ts
  website/pages/docs/theming/advanced.mdx
  website/pages/docs/theming/basic.mdx
  website/pages/docs/theming/create.mdx
  website/pages/docs/theming/modify.mdx
  website/pages/docs/theming/overview.mdx
  website/src/components/theming-guide-image.tsx
Labels: Topic: Component API ⚙️, Topic: Documentation 📚

#1740 fix(website): update "edit this page" url
  website/next.config.js
Labels: Topic: Website 🖥

#1753 fix: fixed useDescendant to register/deregister items based on focuse…
  CONTRIBUTING.md
  packages/descendant/package.json
  packages/descendant/src/use-descendant.ts
  packages/menu/stories/menu.stories.tsx
Labels: Type: Bug 🐛

#1759 docs: restructure `Icon` page
  website/pages/docs/components/icon.mdx
  website/src/components/codeblock/react-live-scope.tsx
  website/src/components/docs/icon.tsx
Labels: Topic: Documentation 📚

#1760 fix(website): add missing docs/components to the sidebar
  website/configs/docs-sidebar.ts
Labels: Topic: Website 🖥

#1527 Test/add a11y tests
  packages/accordion/tests/__snapshots__/accordion.test.tsx.snap
  packages/accordion/tests/accordion.test.tsx
  packages/alert/tests/__snapshots__/alert.test.tsx.snap
  packages/alert/tests/alert.test.tsx
  packages/avatar/tests/__snapshots__/avatar-group.test.tsx.snap
  packages/avatar/tests/__snapshots__/avatar.test.tsx.snap
  packages/avatar/tests/avatar-group.test.tsx
  packages/avatar/tests/avatar.test.tsx
  packages/breadcrumb/tests/__snapshots__/breadcrumb.test.tsx.snap
  packages/breadcrumb/tests/breadcrumb.test.tsx
  packages/button/tests/__snapshots__/button-group.test.tsx.snap
  packages/button/tests/__snapshots__/button.test.tsx.snap
  packages/button/tests/button-group.test.tsx
  packages/button/tests/button.test.tsx
  packages/checkbox/tests/__snapshots__/checkbox.test.tsx.snap
  packages/checkbox/tests/checkbox.test.tsx
  packages/clickable/tests/clickable.test.tsx
  packages/close-button/tests/__snapshots__/close-button.test.tsx.snap
  packages/close-button/tests/close-button.test.tsx
  packages/collapse/tests/__snapshots__/collapse.test.tsx.snap
  packages/collapse/tests/collapse.test.tsx
  packages/control-box/src/control-box.tsx
  packages/control-box/src/index.tsx
  packages/control-box/stories/control-box.stories.tsx
  packages/control-box/tests/__snapshots__/control-box.test.tsx.snap
  packages/control-box/tests/control-box.test.tsx
  packages/drawer/tests/__snapshots__/drawer.test.tsx.snap
  packages/drawer/tests/drawer.test.tsx
  packages/editable/tests/__snapshots__/editable.test.tsx.snap
  packages/editable/tests/editable.test.tsx
  packages/focus-lock/tests/focus-lock.test.tsx
  packages/form-control/tests/__snapshots__/form-control.test.tsx.snap
  packages/form-control/tests/form-control.test.tsx
  packages/icon/tests/__snapshots__/icon.test.tsx.snap
  packages/icon/tests/icon.test.tsx
  packages/image/tests/image.test.tsx
  packages/input/tests/__snapshots__/input.test.tsx.snap
  packages/input/tests/input.test.tsx
  packages/layout/tests/__snapshots__/layout.test.tsx.snap
  packages/layout/tests/layout.test.tsx
  packages/menu/stories/menu.stories.tsx
  packages/menu/tests/menu.test.tsx
  packages/modal/tests/alert-dialog.test.tsx
  packages/modal/tests/modal.test.tsx
  packages/test-utils/src/test-utils.tsx
Labels: Topic: Accessibility (A11y) ♿️, Topic: Testing 🧪

#1793 fix(website): enable team github links
  website/pages/team.tsx
Labels: Topic: Website 🖥

#1795 chore(website): add docs:deploy script
  package.json
Labels: Topic: Website 🖥

#1828 perf(website): improve homepage lighthouse scores
  .all-membersrc
  .all-sponsorsrc
  .gitignore
  package.json
  scripts/all-members.ts
  scripts/avatars.ts
  scripts/image-cache.ts
  tsconfig.json
  website/.gitignore
  website/configs/tweets.json
  website/configs/tweets.ts
  website/layouts/index.tsx
  website/layouts/mdx.tsx
  website/next.config.js
  website/package.json
  website/pages/_app.tsx
  website/pages/docs/components/icon.mdx
  website/pages/docs/data-display/list.mdx
  website/pages/index.tsx
  website/public/logos/tuteria.png
  website/public/logos/usability-hub.png
  website/public/robots.txt
  website/src/components/codeblock/react-live-scope.tsx
  website/src/components/discord-strip.tsx
  website/src/components/footer.tsx
  website/src/components/header.tsx
  website/src/components/page-container.tsx
  website/src/components/tweet-card.tsx
  website/src/components/version-switcher.tsx
  yarn.lock
Labels: Topic: Accessibility (A11y) ♿️, Topic: Performance, Topic: Website 🖥

#1834 chore(button): add color exceptions for yellow and cyan buttons
  packages/button/stories/button.stories.tsx
  packages/theme/src/components/button.ts
  packages/theme/src/foundations/colors.ts
  website/public/avatars/100134.jpg
  website/public/avatars/105573.jpg
  website/public/avatars/105603.jpg
  website/public/avatars/105615.jpg
  website/public/avatars/106035.jpg
  website/public/avatars/106171.jpg
  website/public/avatars/106778.jpg
  website/public/avatars/106866.jpg
  website/public/avatars/107486.jpg
  website/public/avatars/107607.jpg
  website/public/avatars/108493.jpg
  website/public/avatars/111778.jpg
  website/public/avatars/113475.jpg
  website/public/avatars/113610.jpg
  website/public/avatars/113971.jpg
  website/public/avatars/115478.jpg
  website/public/avatars/116146.jpg
  website/public/avatars/119582.jpg
  website/public/avatars/120464.jpg
  website/public/avatars/121032.jpg
  website/public/avatars/51659.jpg
  website/public/avatars/51660.jpg
  website/public/avatars/60720.jpg
  website/public/avatars/60721.jpg
  website/public/avatars/64011.jpg
  website/public/avatars/68336.jpg
  website/public/avatars/75753.jpg
  website/public/avatars/77261.jpg
  website/public/avatars/77345.jpg
  website/public/avatars/77375.jpg
  website/public/avatars/80180.jpg
  website/public/avatars/80834.jpg
  website/public/avatars/82793.jpg
  website/public/avatars/82844.jpg
  website/public/avatars/84888.jpg
  website/public/avatars/86630.jpg
  website/public/avatars/88556.jpg
  website/public/avatars/95802.jpg
  website/public/avatars/96783.jpg
  website/public/avatars/97912.jpg
  website/public/avatars/98173.jpg
  website/public/avatars/98175.jpg
  website/public/avatars/99981.jpg
  website/public/avatars/@aayush.jpg
  website/public/avatars/@colmtuite.jpg
  website/public/avatars/@echobind.jpg
  website/public/avatars/@leeerob.jpg
  website/public/avatars/@mojombo.jpg
  website/public/avatars/@nicktrabue.jpg
  website/public/avatars/@rauchg.jpg
  website/public/avatars/@ryanflorence.jpg
  website/public/avatars/@ssijak.jpg
  website/report.20200826.083946.32215.0.001.json
Labels: Topic: Accessibility (A11y) ♿️

#1803 chore: add pull request template for contributors
  .github/pull_request_template.md
Labels: Topic: Repo Management :globe_with_meridians:

#1841 refactor(docs): remove nextjs optimization
  website/configs/guides-sidebar.ts
  website/pages/guides/nextjs-optimization.mdx
Labels: Topic: Documentation 📚

#1835 docs: updated example to indicate where merge util comes from. removed note about color mode
  website/pages/docs/getting-started.mdx
  website/pages/docs/migration.mdx
Labels: Topic: Documentation 📚

#1849 fix: Update theme export in core package
  packages/core/src/index.tsx
Labels: Topic: Build and Workflow ↩️

#1860 test(tooltip): fix
  packages/tooltip/tests/__snapshots__/tooltip.test.tsx.snap
  packages/tooltip/tests/tooltip.test.tsx
Labels: Topic: Testing 🧪

#1861 chore: fix failing tests
  packages/alert/tests/__snapshots__/alert.test.tsx.snap
  packages/button/tests/button.test.tsx
  packages/checkbox/tests/__snapshots__/checkbox.test.tsx.snap
  packages/editable/tests/editable.test.tsx
  packages/input/tests/__snapshots__/input.test.tsx.snap
  packages/number-input/tests/__snapshots__/number-input.test.tsx.snap
  packages/progress/tests/Progress.test.tsx
  packages/progress/tests/__snapshots__/Progress.test.tsx.snap
  packages/radio/tests/__snapshots__/radio.test.tsx.snap
  packages/radio/tests/radio.test.tsx
  packages/select/tests/__snapshots__/select.test.tsx.snap
  packages/switch/tests/__snapshots__/switch.test.tsx.snap
  packages/textarea/tests/__snapshots__/text-area.test.tsx.snap
  packages/tooltip/tests/__snapshots__/tooltip.test.tsx.snap
Labels: Topic: Testing 🧪

#1864 fix: mock out useId for tests
  jest.config.js
  jest.setup.js
  packages/accordion/jest.config.js
  packages/alert/jest.config.js
  packages/avatar/jest.config.js
  packages/breadcrumb/jest.config.js
  packages/button/jest.config.js
  packages/checkbox/jest.config.js
  packages/clickable/jest.config.js
  packages/close-button/jest.config.js
  packages/collapse/jest.config.js
  packages/color-mode/jest.config.js
  packages/control-box/jest.config.js
  packages/counter/jest.config.js
  packages/css-reset/jest.config.js
  packages/descendant/jest.config.js
  packages/drawer/jest.config.js
  packages/editable/jest.config.js
  packages/focus-lock/jest.config.js
  packages/form-control/jest.config.js
  packages/hooks/jest.config.js
  packages/icon/jest.config.js
  packages/icons/jest.config.js
  packages/image/jest.config.js
  packages/input/jest.config.js
  packages/layout/jest.config.js
  packages/live-region/jest.config.js
  packages/media-query/jest.config.js
  packages/menu/jest.config.js
  packages/modal/jest.config.js
  packages/number-input/jest.config.js
  packages/pin-input/jest.config.js
  packages/pin-input/tests/__snapshots__/pin-input.test.tsx.snap
  packages/popover/jest.config.js
  packages/popper/jest.config.js
  packages/portal/jest.config.js
  packages/progress/jest.config.js
  packages/radio/jest.config.js
  packages/select/jest.config.js
  packages/skeleton/jest.config.js
  packages/skip-nav/jest.config.js
  packages/slider/jest.config.js
  packages/spinner/jest.config.js
  packages/stat/jest.config.js
  packages/styled-system/jest.config.js
  packages/switch/jest.config.js
  packages/system/jest.config.js
  packages/tabs/jest.config.js
  packages/tag/jest.config.js
  packages/textarea/jest.config.js
  packages/theme-tools/jest.config.js
  packages/theme/jest.config.js
  packages/toast/jest.config.js
  packages/tooltip/jest.config.js
  packages/tooltip/tests/__snapshots__/tooltip.test.tsx.snap
  packages/transition/jest.config.js
  packages/utils/jest.config.js
  packages/visually-hidden/jest.config.js
Labels: Topic: Testing 🧪

#1699 chore(workflows): update current workflows to only `pr` + `publish`
  .github/workflows/deploy-website.yml
  .github/workflows/node.yml
  .github/workflows/pr.yml
  .github/workflows/publish.yml
Labels: Topic: Build and Workflow ↩️

#1874 chore: generate changelog for 1.0.0-rc.3
  .gitignore
  CHANGELOG.md
  package.json
Labels: Topic: Repo Management :globe_with_meridians:

#1873 docs: add smart-watch color generator
  website/pages/docs/theming/theme.mdx
Labels: Topic: Documentation 📚

#1871 docs: add Icon Button to sidebar
  website/configs/docs-sidebar.ts
Labels: Topic: Documentation 📚

#1865 chore: unpin dependencies in root and website package.json
  package.json
  website/package.json
  yarn.lock
Labels: Type: Dependency 🔗

#1867 chore(docs): add redirects
  website/configs/docs-sidebar.ts
  website/next.config.js
  website/pages/index.tsx
Labels: Topic: Documentation 📚

#1850 docs: Remove isIndeterminate from Circular Progress docs
  website/pages/docs/feedback/circular-progress.mdx
  website/pages/docs/migration.mdx
Labels: Topic: Documentation 📚

#1883 docs: fix typo
  website/pages/docs/form/radio.mdx
Labels: Topic: Documentation 📚

#1894 chore(issue-templates): add html comments to hide non-essential text blocks
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Topic: Repo Management :globe_with_meridians:

#1906 fix(input-element): increase z-index
  packages/input/src/input-element.tsx
  packages/input/tests/__snapshots__/input.test.tsx.snap
Labels: Type: Bug 🐛
