Repository chakra-ui/chakra-ui, pull requests merged in 2020-10, with the labels that each got.

#2139 Fix/use media query
  examples/create-react-app/src/Logo.tsx
  examples/nextjs-typescript/components/Logo.tsx
  packages/media-query/src/media-query.hook.tsx
  packages/media-query/src/use-media-query.ts
  tooling/cra-template-typescript/template/src/Logo.tsx
  tooling/cra-template/template/src/Logo.js
  website/configs/docs-sidebar.ts
  website/pages/docs/hooks/use-media-query.mdx
  website/pages/docs/hooks/use-prefers-reduced-motion.mdx
Labels: Type: API discussion 💡, Type: Bug 🐛

#2138 docs(breadcrumb): Small correction
  website/pages/docs/components/breadcrumb.mdx
Labels: Topic: Documentation 📚

#2153 fix(avatar): add loading prop for avatar
  packages/avatar/src/avatar.tsx
Labels: Topic: Component API ⚙️

#2132 fix(toast): closeAll method actually closes all
  packages/toast/src/toast-manager.tsx
  packages/toast/src/toast.class.tsx
  packages/toast/src/toast.tsx
  packages/toast/src/toast.types.ts
  packages/toast/src/toast.utils.ts
  packages/toast/src/use-toast.tsx
  packages/toast/stories/toast.stories.tsx
Labels: Type: Bug 🐛

#1805 feat(focus-lock): relax type on focusable refs to handle non-HTMLElement refs
  packages/focus-lock/src/index.tsx
  packages/modal/src/modal.tsx
  packages/popover/src/popover.utils.ts
  packages/popover/src/use-popover.ts
  packages/utils/src/tabbable.ts
Labels: Type: Feature 🚀

#1723 feature(standalone-toasts): create toasts outside of react components
  packages/toast/package.json
  packages/toast/src/index.ts
  packages/toast/src/use-toast.tsx
  packages/toast/test/standalone-toast.test.tsx
  website/pages/docs/feedback/toast.mdx
Labels: Type: Feature 🚀

#2193 docs(checkbox-group): update the props table and add shared style pro…
  website/pages/docs/form/checkbox.mdx
Labels: Topic: Documentation 📚

#2191 feat(toast): allow toast.closeAll position selection
  packages/toast/src/toast-manager.tsx
  packages/toast/src/toast.class.tsx
  packages/toast/src/toast.types.ts
  packages/toast/stories/toast.stories.tsx
  website/pages/docs/feedback/toast.mdx
Labels: Topic: Component API ⚙️

#2196 fix: minor spelling tweaks
  website/pages/docs/layout/wrap.mdx
Labels: Topic: Documentation 📚

#2215 docs(list): fix stylePos to stylePosition
  website/pages/docs/data-display/list.mdx
Labels: Topic: Documentation 📚

#2218 refactor: add index, setIndex to AccordionContext
  packages/accordion/src/use-accordion.ts
Labels: Type: Feature 🚀

#2254 docs(Color Mode): fix typo in Color Mode docs
  website/pages/docs/features/color-mode.mdx
Labels: Topic: Documentation 📚

#2253 fix(utils): properly filter undefined object values
  packages/utils/src/object.ts
  packages/utils/tests/object.test.ts
Labels: Type: Bug 🐛

#2258 docs: Update _groupHover parent role="group" attribute info - 1.0RC
  website/pages/docs/features/style-props.mdx
Labels: Topic: Documentation 📚

#2262 docs(icons): fix typo
  website/pages/docs/components/icon.mdx
Labels: Topic: Documentation 📚

#2228 Feat/use colors
  jest.config.js
  package.json
  packages/hooks/package.json
  packages/styled-system/src/config/layout.ts
  packages/system/src/hooks.ts
  packages/system/tests/hooks.test.ts
  packages/utils/package.json
  packages/utils/src/object.ts
  website/configs/docs-sidebar.ts
  website/pages/docs/hooks/use-token.mdx
  yarn.lock
Labels: Topic: Component API ⚙️

#1464 build(pacakge.json): adding exports field for all packages
  packages/accordion/package.json
  packages/alert/package.json
  packages/avatar/package.json
  packages/breadcrumb/package.json
  packages/button/package.json
  packages/checkbox/package.json
  packages/clickable/package.json
  packages/close-button/package.json
  packages/color-mode/package.json
  packages/control-box/package.json
  packages/core/package.json
  packages/counter/package.json
  packages/css-reset/package.json
  packages/descendant/package.json
  packages/editable/package.json
  packages/focus-lock/package.json
  packages/form-control/package.json
  packages/hooks/package.json
  packages/icon/package.json
  packages/icons/package.json
  packages/image/package.json
  packages/input/package.json
  packages/layout/package.json
  packages/live-region/package.json
  packages/media-query/package.json
  packages/menu/package.json
  packages/modal/package.json
  packages/number-input/package.json
  packages/pin-input/package.json
  packages/popover/package.json
  packages/popper/package.json
  packages/portal/package.json
  packages/progress/package.json
  packages/radio/package.json
  packages/select/package.json
  packages/skeleton/package.json
  packages/skip-nav/package.json
  packages/slider/package.json
  packages/spinner/package.json
  packages/stat/package.json
  packages/styled-system/package.json
  packages/switch/package.json
  packages/system/package.json
  packages/tabs/package.json
  packages/tag/package.json
  packages/textarea/package.json
  packages/theme-tools/package.json
  packages/theme/package.json
  packages/toast/package.json
  packages/tooltip/package.json
  packages/transition/package.json
  packages/utils/package.json
  packages/visually-hidden/package.json
  scripts/template/package.json
Labels: Topic: Build and Workflow ↩️
