Repository chakra-ui/chakra-ui, pull requests merged in 2020-11, with the labels that each got.

#2389 fix(use-callback): allow onChange prop to update updateValue callback
  packages/hooks/src/use-controllable.ts
  packages/hooks/tests/use-controllable.test.tsx
Labels: Type: Bug 🐛

#2391 Docs/improvement
  website/pages/docs/data-display/avatar.mdx
  website/pages/docs/data-display/badge.mdx
  website/pages/docs/data-display/code.mdx
  website/pages/docs/data-display/divider.mdx
  website/pages/docs/data-display/image.mdx
  website/pages/docs/data-display/kbd.mdx
  website/pages/docs/data-display/list.mdx
  website/pages/docs/data-display/stat.mdx
  website/pages/docs/data-display/tag.mdx
Labels: Topic: Documentation 📚

#2416 Docs/invalid navigation links
  website/src/utils/get-route-context.ts
Labels: Type: Bug 🐛

#2419 chore(eslint): add tsconfig parserOptions only for ts,tsx
  .eslintrc
Labels: Topic: Development :computer:

#2435 chore: added example project for gatsby
  examples/gatsby/.eslintrc
  examples/gatsby/.gitignore
  examples/gatsby/.prettierignore
  examples/gatsby/.prettierrc
  examples/gatsby/LICENSE
  examples/gatsby/README.md
  examples/gatsby/gatsby-browser.js
  examples/gatsby/gatsby-config.js
  examples/gatsby/gatsby-node.js
  examples/gatsby/gatsby-ssr.js
  examples/gatsby/package.json
  examples/gatsby/src/@chakra-ui/gatsby-plugin/theme.js
  examples/gatsby/src/components/header.js
  examples/gatsby/src/components/image.js
  examples/gatsby/src/components/layout.css
  examples/gatsby/src/components/layout.js
  examples/gatsby/src/components/seo.js
  examples/gatsby/src/images/gatsby-astronaut.png
  examples/gatsby/src/images/gatsby-icon.png
  examples/gatsby/src/pages/404.js
  examples/gatsby/src/pages/index.js
  examples/gatsby/src/pages/page-2.js
  examples/gatsby/src/pages/using-typescript.tsx
  examples/gatsby/yarn.lock
  tooling/gatsby-plugin/README.md
  website/pages/docs/getting-started.mdx
  website/pages/docs/migration.mdx
  website/pages/guides/integrations/with-gatsby.mdx
Labels: Topic: Tooling 🛠

#2485 docs(default-theme): Add borderRadius key in object
  website/pages/docs/theming/theme.mdx
Labels: Topic: Documentation 📚

#2551 fix(workflow): update PR workflow
  .github/workflows/pr.yml
Labels: Topic: Build and Workflow ↩️

#2625 docs: update toast title prop type to string
  website/pages/docs/feedback/toast.mdx
Labels: Topic: Documentation 📚

#2623 docs: remove info about breakout
  website/pages/docs/components/link.mdx
Labels: Topic: Documentation 📚

#2217 feat(number-input): uses props of wrapping form-control
  .changeset/beige-snails-burn.md
  packages/number-input/package.json
  packages/number-input/src/use-number-input.ts
  packages/number-input/stories/number-input.stories.tsx
  packages/number-input/tests/__snapshots__/number-input.test.tsx.snap
  packages/number-input/tests/number-input.test.tsx
  website/pages/docs/form/form-control.mdx
Labels: Type: Feature 🚀

#2659 feat: added theming to ModalCloseButton
  .changeset/curly-games-repeat.md
  packages/modal/src/modal.tsx
  packages/theme/src/components/modal.ts
Labels: Type: Feature 🚀

#2658 feat: radio uses props of wrapping form control
  .changeset/soft-grapes-smile.md
  packages/radio/package.json
  packages/radio/src/use-radio.ts
  packages/radio/tests/radio.test.tsx
Labels: Type: Feature 🚀

#2657 chore(eslint): enable plugin:react-hooks/recommended
  .eslintrc
  packages/clickable/src/use-clickable.ts
  packages/clickable/src/use-event-listeners.ts
  packages/counter/src/use-counter.ts
  packages/hooks/src/use-focus-on-show.ts
  packages/hooks/src/use-outside-click.ts
  packages/hooks/src/use-unmount-effect.ts
  packages/menu/src/use-menu.ts
  packages/modal/src/modal.tsx
  packages/number-input/src/use-number-input.ts
  packages/pin-input/src/use-pin-input.ts
  packages/popover/src/use-popover.ts
  packages/popper/src/use-popper.ts
  packages/toast/src/toast.tsx
  packages/tooltip/src/use-tooltip.ts
Labels: Topic: Build and Workflow ↩️
