Repository chakra-ui/chakra-ui, pull requests merged in 2020-09, with the labels that each got.

#1910 fix(cra-templates): remove unused props from App Grid
  tooling/cra-template-typescript/template/src/App.tsx
  tooling/cra-template-typescript/template/src/Logo.tsx
  tooling/cra-template/template/src/App.js
Labels: Topic: Tooling 🛠, Type: Bug 🐛

#1909 docs: fix icon imports
  website/pages/docs/form/button.mdx
  website/src/components/codeblock/react-live-scope.tsx
Labels: Topic: Documentation 📚

#1917 chore: update new issue config and templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Topic: Repo Management :globe_with_meridians:

#1911 chore(cra-templates): add lint scripts
  package.json
  tooling/cra-template-typescript/package.json
  tooling/cra-template-typescript/tsconfig.json
  tooling/cra-template-typescript/typings.ts
  tooling/cra-template/package.json
Labels: Topic: Build and Workflow ↩️

#1923 chore: remove useId component snapshots and jest.setup.js
  jest.config.js
  jest.setup.js
  packages/accordion/tests/__snapshots__/accordion.test.tsx.snap
  packages/accordion/tests/accordion.test.tsx
  packages/form-control/tests/__snapshots__/form-control.test.tsx.snap
  packages/form-control/tests/form-control.test.tsx
  packages/modal/tests/__snapshots__/modal.test.tsx.snap
  packages/modal/tests/modal.test.tsx
  packages/pin-input/tests/__snapshots__/pin-input.test.tsx.snap
  packages/pin-input/tests/pin-input.test.tsx
  packages/popover/tests/__snapshots__/popover.test.tsx.snap
  packages/popover/tests/popover.test.tsx
  packages/radio/tests/__snapshots__/radio-group.test.tsx.snap
  packages/radio/tests/__snapshots__/radio.test.tsx.snap
  packages/radio/tests/radio-group.test.tsx
  packages/radio/tests/radio.test.tsx
  packages/slider/tests/__snapshots__/slider.test.tsx.snap
  packages/slider/tests/slider.test.tsx
  packages/tooltip/tests/__snapshots__/tooltip.test.tsx.snap
  packages/tooltip/tests/tooltip.test.tsx
Labels: Topic: Testing 🧪

#1962 test: update snapshots
  packages/alert/tests/__snapshots__/alert.test.tsx.snap
  packages/button/tests/__snapshots__/button.test.tsx.snap
  packages/checkbox/tests/__snapshots__/checkbox.test.tsx.snap
  packages/close-button/tests/__snapshots__/close-button.test.tsx.snap
  packages/icon/tests/__snapshots__/create-icon.test.tsx.snap
  packages/icon/tests/__snapshots__/icon.test.tsx.snap
  packages/stat/tests/__snapshots__/stat.test.tsx.snap
  packages/tag/tests/__snapshots__/tag.test.tsx.snap
Labels: Topic: Testing 🧪

#1904 chore(dependabot): remove configuration to disable automatic updates
  .dependabot/config.yml
Labels: Topic: Repo Management :globe_with_meridians:

#1981 fix(tooling): flip load order of CSSReset and GlobalStyles
  tooling/gatsby-plugin-chakra-ui/gatsby-browser.js
Labels: Topic: Tooling 🛠

#1980 docs: document usage of close/closeAll instance methods
  website/pages/docs/feedback/toast.mdx
Labels: Topic: Documentation 📚

#1611 fix(toast): improve type and layout style with relative units from theme
  packages/toast/src/use-toast.tsx
Labels: Type: Bug 🐛

#1997 fix(alert): improve layout and text/icon alignment
  packages/alert/src/alert.tsx
  packages/alert/tests/__snapshots__/alert.test.tsx.snap
  packages/theme/src/components/alert.ts
  website/pages/docs/feedback/alert.mdx
Labels: Topic: Design and UX ✍️

#1983 docs(accordion): remove references to some AccordionItem props
  website/pages/docs/components/accordion.mdx
Labels: Topic: Documentation 📚

#2019 fix: useStyleConfig omit children when merging
  packages/system/src/use-style-config.ts
Labels: Topic: Performance, Type: Bug 🐛

#2048 fix: MenuButton flex-basis in IE11
  packages/menu/src/menu.tsx
Labels: Topic: Browser Support 🌏

#2053 docs(tabs): fix tabs onchange example colors for dark mode
  website/pages/docs/components/tabs.mdx
Labels: Topic: Documentation 📚

#2027 Feat/improve breakpoints dx
  jest.config.js
  packages/alert/tests/__snapshots__/alert.test.tsx.snap
  packages/media-query/package.json
  packages/media-query/src/create-media-query.ts
  packages/media-query/src/media-query.utils.ts
  packages/media-query/src/use-breakpoint-value.ts
  packages/media-query/src/use-breakpoint.ts
  packages/media-query/tests/create-media-query.test.ts
  packages/media-query/tests/test-data.ts
  packages/media-query/tests/use-breakpoint-value.test.tsx
  packages/styled-system/src/css.ts
  packages/styled-system/tests/css.test.ts
  packages/styled-system/tests/interpolation.test.ts
  packages/system/src/system.ts
  packages/theme-tools/src/breakpoints.ts
  packages/theme-tools/src/index.ts
  packages/theme-tools/tests/breakpoints.test.ts
  packages/theme/src/foundations/breakpoints.ts
  packages/theme/src/index.ts
  packages/utils/src/array.ts
  packages/utils/src/object.ts
  packages/utils/tests/array.test.ts
  website/pages/docs/migration.mdx
Labels: Topic: Theming 🎨, Type: API discussion 💡

#2073 docs(modal): make close buttons close the modals
  packages/modal/stories/modal.stories.tsx
  website/pages/docs/overlay/modal.mdx
Labels: Topic: Documentation 📚

#1939 revert color mode to rc.2
  .all-membersrc
  .all-sponsorsrc
  .storybook/preview.tsx
  README.md
  examples/create-react-app/src/index.tsx
  examples/next-js/package.json
  examples/next-js/pages/_app.js
  examples/next-js/pages/_document.js
  examples/next-js/pages/index.js
  examples/next-js/src/Chakra.js
  examples/nextjs-typescript/Chakra.tsx
  examples/nextjs-typescript/pages/_app.tsx
  examples/nextjs-typescript/pages/index.tsx
  examples/nextjs-typescript/pages/properties/[id].tsx
  examples/nextjs-typescript/pages/properties/index.tsx
  examples/nextjs-typescript/tsconfig.json
  packages/color-mode/src/color-mode-provider.tsx
  packages/color-mode/src/color-mode-script.tsx
  packages/color-mode/src/color-mode.utils.ts
  packages/color-mode/src/index.ts
  packages/color-mode/src/storage-manager.ts
  packages/color-mode/test/storage-manager.test.ts
  packages/core/src/chakra-provider.tsx
  packages/portal/tests/__snapshots__/portal.test.tsx.snap
  packages/portal/tests/portal.test.tsx
  packages/test-utils/src/test-utils.tsx
  packages/theme/src/index.ts
  tooling/cra-template-typescript/template/src/App.tsx
  tooling/cra-template-typescript/template/src/test-utils.tsx
  tooling/cra-template/template/src/App.js
  tooling/cra-template/template/src/test-utils.js
  website/layouts/mdx.tsx
  website/package.json
  website/pages/404.tsx
  website/pages/_app.tsx
  website/pages/_document.tsx
  website/pages/docs/features/color-mode.mdx
  website/pages/docs/getting-started.mdx
  website/pages/docs/migration.mdx
  website/pages/guides/with-nextjs-font-files.mdx
  website/pages/index.tsx
  website/pages/team.tsx
  website/src/components/chakra.tsx
  website/src/components/font-face.tsx
  website/src/types/github.ts
  yarn.lock
Labels: Topic: Color Mode 🌓, Topic: Next.js ▲, Topic: SSR 💻

#2089 Fix/color mode
  examples/create-react-app/package.json
  examples/create-react-app/src/index.tsx
  examples/next-js/package.json
  examples/next-js/pages/_app.js
  examples/next-js/pages/_document.js
  examples/next-js/src/Chakra.js
  examples/nextjs-typescript/Chakra.tsx
  examples/nextjs-typescript/components/Logo.tsx
  examples/nextjs-typescript/components/logo.svg
  examples/nextjs-typescript/pages/_document.tsx
  packages/color-mode/src/color-mode-provider.tsx
  packages/color-mode/src/color-mode-script.tsx
  packages/core/src/chakra-provider.tsx
  tooling/cra-template-typescript/package.json
  tooling/cra-template-typescript/template.json
  tooling/cra-template-typescript/template/src/index.tsx
  tooling/cra-template/package.json
  tooling/cra-template/template.json
  tooling/cra-template/template/src/index.js
  website/pages/docs/components/link.mdx
  website/pages/docs/features/color-mode.mdx
  website/pages/docs/migration.mdx
Labels: Topic: Color Mode 🌓, Type: Bug 🐛

#2104 docs(accordion): remove reference to AccordionItem defaultIsOpen prop
  website/pages/docs/components/accordion.mdx
Labels: Topic: Documentation 📚

#2114 fix(colormode): csr and hydration issues
  examples/create-react-app/src/App.tsx
  examples/create-react-app/src/ColorModeSwitcher.tsx
  examples/create-react-app/src/Logo.tsx
  examples/create-react-app/src/index.tsx
  examples/create-react-app/src/logo.svg
  packages/color-mode/src/color-mode-provider.tsx
  packages/color-mode/src/color-mode.utils.ts
  packages/color-mode/test/color-mode-provider.test.tsx
  packages/color-mode/test/color-mode-provider__browser.test.tsx
  packages/color-mode/test/color-mode-provider__server.test.tsx
  packages/color-mode/test/dark-mode.test.tsx
  packages/color-mode/test/light-mode.test.tsx
  packages/color-mode/test/use-color-mode-value.test.tsx
  packages/color-mode/test/utils.tsx
Labels: Topic: Color Mode 🌓, Type: Bug 🐛
