Repository chakra-ui/chakra-ui, pull requests merged in 2020-06, with the labels that each got.

#794 fix(select): remove duplicate Select arrow in ie11
  packages/css-reset/src/CSSReset.tsx
Labels: Topic: Browser Support 🌏

#787 docs: fix nav link ordering
  docs/src/components/docs/side-nav.js
Labels: Topic: Documentation 📚

#788 docs: fix start command
  docs/pages/contributing.mdx
  package.json
Labels: Topic: Documentation 📚

#789 docs(contributing): add documentation goals
  docs/pages/contributing.mdx
Labels: Topic: Documentation 📚

#805 docs(guides): add file contributors functionality
  docs/gatsby-node.js
  docs/src/pages/guides.js
  docs/src/templates/guides.js
  docs/utils.js
Labels: Topic: Website 🖥

#810 docs(guides): fix guide contributors functionality
  docs/gatsby-node.js
  docs/pages/guides/with-framer.mdx
  docs/pages/guides/with-rhf.mdx
  docs/src/pages/guides.js
  docs/src/templates/guides.js
  docs/utils.js
Labels: Topic: Website 🖥

#812 docs: edit existing content
  docs/pages/color-mode.mdx
  docs/pages/components/accordion.mdx
  docs/pages/components/alert.mdx
  docs/pages/components/alertdialog.mdx
  docs/pages/components/avatar.mdx
  docs/pages/components/badge.mdx
  docs/pages/components/breadcrumb.mdx
  docs/pages/components/button.mdx
  docs/pages/components/checkbox.mdx
  docs/pages/components/circularprogress.mdx
  docs/pages/components/closebutton.mdx
  docs/pages/components/collapse.mdx
  docs/pages/components/editable.mdx
  docs/pages/components/formcontrol.mdx
  docs/pages/components/heading.mdx
  docs/pages/components/icon.mdx
  docs/pages/components/iconbutton.mdx
  docs/pages/components/input.mdx
  docs/pages/components/keyboardkey.mdx
  docs/pages/components/link.mdx
  docs/pages/components/list.mdx
  docs/pages/components/menu.mdx
  docs/pages/components/modal.mdx
  docs/pages/components/numberinput.mdx
  docs/pages/components/popover.mdx
  docs/pages/components/text.mdx
  docs/pages/contributing.mdx
  docs/pages/migration.mdx
  docs/pages/principles.mdx
  docs/pages/responsive-styles.mdx
  docs/pages/style-props.mdx
  docs/pages/theming/theme.mdx
  packages/system/package.json
Labels: Topic: Documentation 📚

#815 fix(core): add Skeleton export
  packages/core/package.json
  packages/core/src/index.tsx
Labels: Type: Bug 🐛

#818 chore(site): add seo to guides page
  docs/src/pages/guides.js
Labels: Topic: Website 🖥

#814 chore(site): add team page
  docs/gatsby-config.js
  docs/gatsby-node.js
  docs/package.json
  docs/src/components/header.js
  docs/src/pages/team.js
  docs/utils.js
  yarn.lock
Labels: Topic: Website 🖥

#817 chore(site): adjust metadata
  docs/gatsby-config.js
Labels: Topic: Website 🖥

#831 chore(github): re-add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Topic: Tooling 🛠

#834 chore(stale): re-add configuration
  .github/stale.yml
Labels: Topic: Tooling 🛠

#848 chore(dependabot): fix configs
  .dependabot/config.yml
Labels: Topic: Tooling 🛠

#861 chore(site): move from github api v4 to v3 for team page
  docs/gatsby-config.js
  docs/gatsby-node.js
  docs/package.json
  docs/src/pages/team.js
  docs/utils.js
  yarn.lock
Labels: Topic: Website 🖥

#862 chore(site): add seo to index page
  docs/src/pages/index.jsx
Labels: Topic: Website 🖥

#868 chore(site): add optional octokit auth via .env
  website/gatsby-config.js
  website/utils.js
Labels: Topic: Website 🖥

#886 docs(guides): add "how to create a guide" guide
  website/guides/how-to-create-a-guide.mdx
Labels: Topic: Website 🖥

#887 docs: fix form pagination ordering
  website/utils.js
Labels: Topic: Website 🖥

#875 docs/mobile navigation
  website/src/components/algolia-search.js
  website/src/components/bottom-nav.js
  website/src/components/header.js
  website/src/components/layout.js
Labels: Topic: Website 🖥

#832 feat(divider): revise divider and add vertical support
  docs/pages/layout/divider.mdx
  packages/layout/src/divider.tsx
  packages/layout/src/stories/divider.stories.tsx
  packages/theme/src/components/divider.ts
  packages/theme/src/components/index.ts
Labels: Topic: Documentation 📚, Type: Feature 🚀

#923 fix(codesandbox): filter private test-utils pkg
  .codesandbox/ci.json
Labels: Topic: Tooling 🛠

#987 docs(toast): updated documentation for toast component
  website/docs/components/toast.mdx
Labels: Topic: Documentation 📚

#988 docs: add icon migration notes
  website/docs/components/icon.mdx
  website/docs/migration.mdx
  website/docs/theming/theme.mdx
Labels: Topic: Documentation 📚

#986 fix bad path in accordion/package.json
  packages/accordion/package.json
Labels: Type: Bug 🐛

#978 fix: updated the transition components in modal docs and migration guide
  website/docs/components/modal.mdx
  website/docs/migration.mdx
Labels: Topic: Documentation 📚

#921 feat(media-query): add breakpoint value, animation, and color mode utils
  packages/media-query/src/media-query.hook.tsx
  packages/media-query/stories/media-query.stories.tsx
Labels: Type: Feature 🚀

#1012 feat(image): image lazy loading support
  packages/image/src/image.tsx
Labels: Type: Feature 🚀

#1016 docs(editable): fix the custom controls example
  website/docs/components/editable.mdx
  website/docs/migration.mdx
Labels: Topic: Documentation 📚

#1047 fix(stack): default align-items css value
  packages/layout/src/stack.tsx
Labels: Topic: Design and UX ✍️

#1050 fix: Adding Icon to theme export
  packages/theme/src/components/index.ts
Labels: Topic: Theming 🎨, Type: Bug 🐛

#1054 docs: added useBreakpointValue hook documentation to the website
  website/docs/hooks/use-breakpoint-value.mdx
Labels: Topic: Documentation 📚

#1049 fix: Adding PIN input to core export
  packages/core/src/index.tsx
  website/docs/form/pin-input.mdx
Labels: Type: Bug 🐛

#1059 docs: changing color to color scheme for switch
  website/docs/form/switch.mdx
Labels: Topic: Documentation 📚
