Repository chakra-ui/chakra-ui, pull requests merged in 2020-05, with the labels that each got.

#730 fix(gatsby-plugin): add react import to gatsby-ssr
  tooling/gatsby-plugin-chakra-ui/gatsby-ssr.js
Labels: Type: Bug 🐛

#743 chore(lint-staged): clean up and fix lintstagedrc
  .lintstagedrc
Labels: Topic: Tooling 🛠

#742 chore(website): add canonical urls
  docs/gatsby-config.js
  docs/package.json
  docs/src/components/seo.js
  docs/src/templates/docs.js
  yarn.lock
Labels: Topic: Website 🖥

#741 fix(docs): updated gatsby-plugin-manifest options from starter values
  docs/gatsby-config.js
Labels: Topic: Website 🖥

#698 [v1] feat/migration docs
  website/pre-docs/migration.md
Labels: Topic: Documentation 📚

#735 docs: correct unclear heading
  packages/chakra-ui-docs/pages/modal.mdx
Labels: Topic: Documentation 📚

#693 fix: add on close callback in useToast
  packages/chakra-ui/src/Toast/index.js
Labels: Type: Bug 🐛

#686 fix: add support for custom icon set
  packages/chakra-ui/src/theme/icons.d.ts
Labels: Type: Bug 🐛

#740 fix: #739 ColorModeProvider correctly use manual mode
  packages/chakra-ui/src/ColorModeProvider/index.js
Labels: Type: Bug 🐛

#755 fix(dependabot): update label
  .dependabot/config.yml
Labels: Topic: Tooling 🛠

#752 chore(website): add search, toc, and pagination
  .eslintrc
  docs/gatsby-config.js
  docs/gatsby-node.js
  docs/package.json
  docs/pages/components/menu.mdx
  docs/pages/components/modal.mdx
  docs/pages/components/progress.mdx
  docs/src/components/docs/ColorPalette.js
  docs/src/components/docs/MDXComponents.jsx
  docs/src/components/header.js
  docs/src/components/layout.js
  docs/src/components/pagination.js
  docs/src/components/search.js
  docs/src/components/toc.js
  docs/src/styles/algolia.css
  docs/src/templates/docs.js
  docs/utils.js
  docs/utils.spec.js
  yarn.lock
Labels: Topic: Website 🖥

#754 chore(storybook): upgrade to 6.0.0-beta
  .storybook/main.js
  .storybook/preview.tsx
  .storybook/tsconfig.json
  package.json
  yarn.lock
Labels: Topic: Tooling 🛠

#749 update Button loadingText type
  packages/chakra-ui/src/Button/index.d.ts
Labels: Type: Bug 🐛

#771 Fix typos
  packages/chakra-ui-docs/pages/editable.mdx
  packages/chakra-ui-docs/pages/principles.mdx
  packages/chakra-ui-docs/pages/tabs.mdx
  packages/chakra-ui/src/FormControl/examples.js
Labels: Topic: Documentation 📚

#695 docs: create website docs for theming api
  docs/pages/component-themes.mdx
  docs/pages/contributing.mdx
  docs/pages/recipes.mdx
Labels: Topic: Documentation 📚

#775 docs: add github edit link to docs pages
  docs/gatsby-config.js
  docs/gatsby-node.js
  docs/src/components/github-edit-link.js
  docs/src/templates/docs.js
  docs/utils.js
Labels: Topic: Documentation 📚
