Repository chakra-ui/chakra-ui, pull requests merged in 2020-07, with the labels that each got.

#1078 feat: added forwardRef to HStack and VStack
  packages/layout/src/stack.tsx
Labels: Topic: Component API ⚙️

#992 fix(preview-html): classlist null when devtools open - storybook
  .storybook/preview-head.html
Labels: Topic: Tooling 🛠

#884 feat: allow responsive pseudo props with object notation
  packages/css/src/css.ts
  packages/css/src/css.types.ts
  packages/css/tests/css.test.ts
  packages/layout/src/aspect-ratio.tsx
  packages/layout/stories/aspect-ratio.stories.tsx
  packages/utils/src/responsive.ts
  packages/utils/tests/responsive.test.ts
Labels: Type: Bug 🐛

#937 docs: introduce global theming sooner
  CONTRIBUTING.md
  website/docs/style-props.mdx
  website/docs/theming/basic.mdx
  website/docs/theming/overview.mdx
Labels: Topic: Documentation 📚

#1136 chore(site): fix github link
  website/src/components/header.js
Labels: Topic: Website 🖥

#1125 docs(tag): fix and update examples for tag component
  website/docs/components/icon.mdx
  website/docs/components/tag.mdx
  website/docs/form/button.mdx
Labels: Topic: Documentation 📚

#1097 feat(tooltip):Provide a prop for disabling a tooltip.
  packages/tooltip/src/use-tooltip.ts
  packages/tooltip/tests/__snapshots__/tooltip.test.tsx.snap
  packages/tooltip/tests/tooltip.test.tsx
  website/docs/components/tooltip.mdx
Labels: Type: Feature 🚀

#1143 chore: update internal peer deps to ^1.0.0-next.4
  packages/accordion/package.json
  packages/alert-dialog/package.json
  packages/alert/package.json
  packages/avatar/package.json
  packages/breadcrumb/package.json
  packages/button/package.json
  packages/checkbox/package.json
  packages/close-button/package.json
  packages/collapse/package.json
  packages/drawer/package.json
  packages/editable/package.json
  packages/form-control/package.json
  packages/icon/package.json
  packages/icons/package.json
  packages/image/package.json
  packages/input/package.json
  packages/layout/package.json
  packages/media-query/package.json
  packages/menu/package.json
  packages/modal/package.json
  packages/number-input/package.json
  packages/pin-input/package.json
  packages/popover/package.json
  packages/progress/package.json
  packages/radio/package.json
  packages/select/package.json
  packages/skip-nav/package.json
  packages/slider/package.json
  packages/spinner/package.json
  packages/stat/package.json
  packages/switch/package.json
  packages/tabs/package.json
  packages/tag/package.json
  packages/textarea/package.json
  packages/theme-tools/package.json
  packages/theme/package.json
  packages/toast/package.json
  packages/tooltip/package.json
  packages/visually-hidden/package.json
  tooling/gatsby-plugin-chakra-ui/package.json
Labels: Topic: Build and Workflow ↩️, Type: Bug 🐛

#1038 docs: added commit convention in contribution guide
  CONTRIBUTING.md
Labels: Topic: Documentation 📚

#1156 chore: fix new packages
  packages/control-box/README.md
  packages/control-box/package.json
Labels: Topic: Build and Workflow ↩️

#1126 docs(tooltip): update tooltip docs with bug fixes
  packages/tooltip/src/tooltip.tsx
  packages/tooltip/src/use-tooltip.ts
  packages/tooltip/stories/tooltip.stories.tsx
  website/docs/components/tooltip.mdx
Labels: Topic: Component API ⚙️, Topic: Documentation 📚

#1168 docs(theming): fix BadgeSpec import
  website/docs/theming/basic.mdx
  website/docs/theming/overview.mdx
Labels: Topic: Documentation 📚

#1165 docs(tabs): replace useTabsThemingContext
  website/docs/components/tabs.mdx
Labels: Topic: Documentation 📚

#1175 docs(index): fix typo fontsize to fontSize
  website/src/pages/index.js
Labels: Topic: Documentation 📚

#1179 docs(breadcrumb): fix broken example links
  website/docs/components/breadcrumb.mdx
Labels: Topic: Documentation 📚

#1176 chore: deploy website on master push
  .github/workflows/deploy-website.yml
  vercel.json
Labels: Topic: Build and Workflow ↩️, Topic: Website 🖥

#1171 chore(color): make color hex to uppercase for consistent
  packages/theme/src/foundations/colors.ts
Labels: Type: Feature 🚀

#1163 docs(avatar): add wrap to stack containers
  website/docs/components/avatar.mdx
Labels: Topic: Documentation 📚

#1167 docs(switch): wrap usage code with FormControl
  website/docs/form/switch.mdx
Labels: Topic: Documentation 📚

#1185 fix: #1180 slider moving incorrectly when min is odd and step is even
  packages/slider/src/use-slider.ts
  packages/slider/stories/slider.stories.tsx
  packages/utils/src/number.ts
  packages/utils/tests/number.test.ts
Labels: Type: Bug 🐛

#1184 fix: tabs align prop didnt do anything
  packages/tabs/src/tabs.tsx
  packages/theme/src/components/tabs.ts
Labels: Type: Bug 🐛

#1192 chore(nextjs): update next js and ts package imports
  examples/next-js/package.json
  examples/next-js/pages/_app.js
  examples/next-js/pages/_document.js
  examples/next-js/pages/index.js
  examples/nextjs-typescript/package.json
  examples/nextjs-typescript/pages/_app.tsx
  examples/nextjs-typescript/pages/index.tsx
Labels: Topic: Next.js ▲

#1219 chore: initialize changesets
  .changeset/README.md
  .changeset/config.json
  .changeset/pre.json
  .changeset/pretty-icons-rule.md
  examples/create-react-app/package.json
  examples/next-js/package.json
  package.json
  website/package.json
  yarn.lock
Labels: Topic: Tooling 🛠

#1224 test: resolve failing test suite issues
  .changeset/chilled-scissors-occur.md
  .changeset/lucky-chefs-press.md
  .changeset/small-steaks-refuse.md
  packages/accordion/tests/__snapshots__/accordion.test.tsx.snap
  packages/alert-dialog/stories/alert-dialog.stories.tsx
  packages/alert/tests/__snapshots__/alert.test.tsx.snap
  packages/avatar/tests/__snapshots__/avatar-group.test.tsx.snap
  packages/avatar/tests/__snapshots__/avatar.test.tsx.snap
  packages/breadcrumb/tests/__snapshots__/breadcrumb.test.tsx.snap
  packages/button/tests/__snapshots__/button-group.test.tsx.snap
  packages/button/tests/__snapshots__/button.test.tsx.snap
  packages/checkbox/tests/__snapshots__/checkbox.test.tsx.snap
  packages/clickable/tests/clickable.test.tsx
  packages/close-button/tests/__snapshots__/close-button.test.tsx.snap
  packages/drawer/tests/__snapshots__/drawer.test.tsx.snap
  packages/editable/tests/__snapshots__/editable.test.tsx.snap
  packages/form-control/stories/form-control.stories.tsx
  packages/form-control/tests/__snapshots__/form-control.test.tsx.snap
  packages/form-control/tests/form-control.test.tsx
  packages/icon/tests/__snapshots__/icon.test.tsx.snap
  packages/input/tests/__snapshots__/input.test.tsx.snap
  packages/layout/stories/divider.stories.tsx
  packages/layout/tests/__snapshots__/layout.test.tsx.snap
  packages/modal/tests/__snapshots__/modal.test.tsx.snap
  packages/modal/tests/modal.test.tsx
  packages/number-input/stories/number-input.stories.tsx
  packages/number-input/tests/__snapshots__/number-input.test.tsx.snap
  packages/popover/src/use-popover.ts
  packages/popover/tests/__snapshots__/popover.test.tsx.snap
  packages/popover/tests/popover.test.tsx
  packages/progress/tests/__snapshots__/Progress.test.tsx.snap
  packages/radio/tests/__snapshots__/radio.test.tsx.snap
  packages/select/src/select.tsx
  packages/select/tests/__snapshots__/select.test.tsx.snap
  packages/slider/tests/__snapshots__/slider.test.tsx.snap
  packages/slider/tests/slider.test.tsx
  packages/spinner/tests/__snapshots__/spinner.test.tsx.snap
  packages/stat/tests/__snapshots__/stat.test.tsx.snap
  packages/switch/tests/__snapshots__/switch.test.tsx.snap
  packages/tag/src/tag.tsx
  packages/tag/tests/__snapshots__/tag.test.tsx.snap
  packages/textarea/tests/__snapshots__/text-area.test.tsx.snap
  packages/tooltip/tests/__snapshots__/tooltip.test.tsx.snap
  packages/tooltip/tests/tooltip.test.tsx
  packages/transition/tests/utils.test.ts
  packages/visually-hidden/tests/visually-hidden.test.tsx
Labels: Topic: Testing 🧪

#1243 fix: added ColorModeOptions type to theme config
  .changeset/angry-buses-camp.md
  packages/color-mode/src/index.ts
  packages/color-mode/src/use-color-mode-state.ts
  packages/theme/src/index.ts
Labels: Topic: Color Mode 🌓, Topic: TypeScript 🤠

#936 feat(tooling): create js and ts CRA templates
  README.md
  tooling/cra-template-typescript/README.md
  tooling/cra-template-typescript/package.json
  tooling/cra-template-typescript/template.json
  tooling/cra-template-typescript/template/README.md
  tooling/cra-template-typescript/template/gitignore
  tooling/cra-template-typescript/template/public/favicon.ico
  tooling/cra-template-typescript/template/public/index.html
  tooling/cra-template-typescript/template/public/logo192.png
  tooling/cra-template-typescript/template/public/logo512.png
  tooling/cra-template-typescript/template/public/manifest.json
  tooling/cra-template-typescript/template/public/robots.txt
  tooling/cra-template-typescript/template/src/App.test.tsx
  tooling/cra-template-typescript/template/src/App.tsx
  tooling/cra-template-typescript/template/src/ColorModeSwitcher.tsx
  tooling/cra-template-typescript/template/src/Logo.tsx
  tooling/cra-template-typescript/template/src/index.tsx
  tooling/cra-template-typescript/template/src/logo.svg
  tooling/cra-template-typescript/template/src/react-app-env.d.ts
  tooling/cra-template-typescript/template/src/reportWebVitals.ts
  tooling/cra-template-typescript/template/src/serviceWorker.ts
  tooling/cra-template-typescript/template/src/setupTests.ts
  tooling/cra-template-typescript/template/src/test-utils.tsx
  tooling/cra-template/README.md
  tooling/cra-template/package.json
  tooling/cra-template/template.json
  tooling/cra-template/template/.prettierrc
  tooling/cra-template/template/README.md
  tooling/cra-template/template/gitignore
  tooling/cra-template/template/public/favicon.ico
  tooling/cra-template/template/public/index.html
  tooling/cra-template/template/public/logo192.png
  tooling/cra-template/template/public/logo512.png
  tooling/cra-template/template/public/manifest.json
  tooling/cra-template/template/public/robots.txt
  tooling/cra-template/template/src/App.js
  tooling/cra-template/template/src/App.test.js
  tooling/cra-template/template/src/ColorModeSwitcher.js
  tooling/cra-template/template/src/Logo.js
  tooling/cra-template/template/src/index.js
  tooling/cra-template/template/src/logo.svg
  tooling/cra-template/template/src/reportWebVitals.js
  tooling/cra-template/template/src/serviceWorker.js
  tooling/cra-template/template/src/setupTests.js
  tooling/cra-template/template/src/test-utils.js
  website/guides/cra-templates.mdx
  yarn.lock
Labels: Topic: Documentation 📚, Topic: Tooling 🛠

#1301 fix: typo in responsive-styles
  website/docs/responsive-styles.mdx
Labels: Topic: Documentation 📚

#1333 chore(vercel): add /discord invite redirect
  vercel.json
Labels: Topic: Build and Workflow ↩️

#1332 fix(menu): update MenuOption isChecked prop to boolean type
  .changeset/friendly-rivers-breathe.md
  packages/menu/src/use-menu.ts
Labels: Topic: TypeScript 🤠, Type: Bug 🐛

#1327 docs(tooling): update cra ts template readme with correct usage
  tooling/cra-template-typescript/README.md
Labels: Topic: Documentation 📚, Topic: Tooling 🛠

#1328 fix: use next docs link in cra templates
  tooling/cra-template-typescript/template/src/App.tsx
  tooling/cra-template/template/src/App.js
Labels: Topic: Tooling 🛠

#1307 docs(contributing): add changesets overview to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Topic: Documentation 📚

#1304 docs: use git for accurate file history dates
  website/gatsby-node.js
  website/package.json
  website/src/components/github-edit-link.js
  website/src/pages/guides.js
  website/src/templates/docs.js
  website/src/templates/guides.js
  website/utils.js
  website/utils.spec.js
  yarn.lock
Labels: Topic: Documentation 📚

#1359 fix(toast): status types
  website/docs/components/toast.mdx
Labels: Topic: Documentation 📚

#1358 Fix `lineHeights.none` in the theme docs
  website/docs/theming/theme.mdx
Labels: Topic: Documentation 📚

#1366 fix(ci): add Chakra packages build step to deploy-website
  .github/workflows/deploy-website.yml
Labels: Topic: Build and Workflow ↩️, Topic: Website 🖥

#1343 docs(breadcrumb): removes obviously from documentation
  packages/breadcrumb/README.md
Labels: Topic: Documentation 📚

#1305 docs: add minimum typescript version notes
  website/docs/getting-started.mdx
  website/docs/migration.mdx
Labels: Topic: Documentation 📚, Topic: TypeScript 🤠

#1331 docs: update installation instructions and add link to next docs in readme
  README.md
  website/docs/getting-started.mdx
Labels: Topic: Documentation 📚

#1392 fix(icons): Fix viewBox on DragHandleIcon
  packages/icons/src/DragHandle.tsx
Labels: Type: Bug 🐛

#1385 docs(migration): Add missing migration step for Tooltip
  packages/tooltip/migration.md
Labels: Topic: Documentation 📚

#1396 chore(storybook): add color mode toggle button to stories
  .storybook/preview.tsx
Labels: Topic: Storybook 📖

#1306 feat(icons): add hamburger/menu icon to default iconset
  .changeset/three-rules-beg.md
  packages/icons/src/Hamburger.tsx
  packages/icons/src/index.tsx
  website/src/components/icons-list.js
Labels: Type: Feature 🚀

#1349 test(icon): remove presentation role from rendered icon snapshots
  packages/icon/tests/__snapshots__/icon.test.tsx.snap
Labels: Topic: Testing 🧪

#1403 docs(getting-started): remove mention of chakra-cli
  website/docs/migration.mdx
Labels: Topic: Documentation 📚

#1405 fix(docs): adapt to changes
  website/docs/form/pin-input.mdx
Labels: Topic: Documentation 📚

#1411 docs(link): remove disabled prop
  website/docs/components/link.mdx
Labels: Topic: Documentation 📚

#1401 chore: fix failing tests and types
  examples/create-react-app/package.json
  package.json
  packages/accordion/src/accordion.tsx
  packages/accordion/tests/__snapshots__/accordion.test.tsx.snap
  packages/alert/tests/__snapshots__/alert.test.tsx.snap
  packages/avatar/tests/__snapshots__/avatar-group.test.tsx.snap
  packages/button/tests/__snapshots__/button.test.tsx.snap
  packages/checkbox/tests/__snapshots__/checkbox.test.tsx.snap
  packages/close-button/tests/__snapshots__/close-button.test.tsx.snap
  packages/form-control/tests/__snapshots__/form-control.test.tsx.snap
  packages/form-control/tests/form-control.test.tsx
  packages/input/tests/__snapshots__/input.test.tsx.snap
  packages/menu/stories/menu.stories.tsx
  packages/modal/stories/transition.stories.tsx
  packages/modal/tests/__snapshots__/modal.test.tsx.snap
  packages/number-input/stories/number-input.stories.tsx
  packages/number-input/tests/__snapshots__/number-input.test.tsx.snap
  packages/popover/src/use-popover.ts
  packages/popover/tests/__snapshots__/popover.test.tsx.snap
  packages/popover/tests/popover.test.tsx
  packages/progress/tests/__snapshots__/Progress.test.tsx.snap
  packages/radio/tests/__snapshots__/radio.test.tsx.snap
  packages/select/stories/select.stories.tsx
  packages/select/tests/__snapshots__/select.test.tsx.snap
  packages/slider/tests/__snapshots__/slider.test.tsx.snap
  packages/slider/tests/slider.test.tsx
  packages/stat/tests/__snapshots__/stat.test.tsx.snap
  packages/tag/tests/__snapshots__/tag.test.tsx.snap
  packages/textarea/tests/__snapshots__/text-area.test.tsx.snap
  packages/tooltip/src/use-tooltip.ts
  packages/tooltip/tests/__snapshots__/tooltip.test.tsx.snap
  tooling/babel-plugin-chakra-ui/package.json
  yarn.lock
Labels: Topic: Testing 🧪, Topic: TypeScript 🤠
