Repository chakra-ui/chakra-ui, pull requests merged in 2020-12, with the labels that each got.

#2632 chore(extend-theme): improve theme override typings
  .changeset/unlucky-games-happen.md
  packages/react/src/extend-theme.ts
Labels: Topic: TypeScript 🤠, Type: Feature 🚀

#2669 docs(contributing): add details to "Steps to PR"
  CONTRIBUTING.md
Labels: Topic: Repo Management :globe_with_meridians:

#2589 docs: add search
  .all-sponsorsrc
  .changeset/cold-ants-battle.md
  examples/next-js/package.json
  examples/nextjs-typescript/package.json
  package.json
  packages/layout/src/stack.tsx
  scripts/get-search-meta.ts
  website/configs/docs-sidebar.json
  website/configs/docs-sidebar.ts
  website/configs/guides-sidebar.json
  website/configs/guides-sidebar.ts
  website/configs/search-meta.json
  website/layouts/mdx.tsx
  website/package.json
  website/pages/_app.tsx
  website/pages/docs/migration.mdx
  website/pages/index.tsx
  website/src/components/algolia-search.tsx
  website/src/components/container.tsx
  website/src/components/header.tsx
  website/src/components/omni-search.tsx
  website/src/components/search.styles.tsx
  website/src/components/sidebar/sidebar-icons.tsx
  website/src/components/sidebar/sidebar-link.tsx
  website/src/components/sidebar/sidebar.tsx
  website/src/styles/algolia.css
  website/theme.ts
  yarn.lock
Labels: Topic: Website 🖥

#2665 fix(theme): add "description" to parts array for alert
  packages/theme/src/components/alert.ts
Labels: Type: Bug 🐛

#1782 feature(blog): add a blog section to the website
  .changeset/beige-snails-burn.md
  .changeset/sharp-tables-change.md
  .changeset/unlucky-games-happen.md
  README.md
  packages/layout/src/container.tsx
  packages/layout/src/divider.tsx
  packages/layout/stories/container.stories.tsx
  packages/layout/tests/layout.test.tsx
  website/configs/blog-sidebar.json
  website/configs/docs-sidebar.json
  website/layouts/index.tsx
  website/layouts/mdx.tsx
  website/pages/blog/chakra-v1-just-landed.mdx
  website/pages/blog/index.tsx
  website/src/components/blog-post-card.tsx
  website/src/components/chakra.tsx
  website/src/components/page-container.tsx
  website/src/components/sidebar/sidebar.tsx
  website/src/utils/calc-read-time.ts
  website/src/utils/get-blog-posts.ts
  website/src/utils/get-route-context.ts
  website/src/utils/load-mdx-dir.ts
  website/src/utils/mdx-utils.js
Labels: Topic: Website 🖥

#2653 fix: add colors object to match whatsapp branding
  packages/theme/src/foundations/colors.ts
Labels: Topic: Design and UX ✍️

#2678 docs: Mention mandatory version update explicitly
  website/pages/docs/migration.mdx
Labels: Topic: Documentation 📚

#2648 feat(table): table component
  package.json
  packages/react/package.json
  packages/react/src/index.tsx
  packages/table/README.md
  packages/table/jest.config.js
  packages/table/package.json
  packages/table/src/index.ts
  packages/table/src/table.tsx
  packages/table/stories/double-header-table.stories.tsx
  packages/table/stories/react-table.stories.tsx
  packages/table/stories/table.stories.tsx
  packages/table/tests/table.test.tsx
  packages/table/tsconfig.json
  packages/theme/src/components/index.ts
  packages/theme/src/components/table.ts
  website/configs/docs-sidebar.json
  website/pages/docs/data-display/table.mdx
  website/src/components/props-table.tsx
  yarn.lock
Labels: Type: Feature 🚀

#2708 fix(drawer): close button styles
  .changeset/forty-goats-pull.md
  packages/close-button/src/close-button.tsx
  packages/theme/src/components/drawer.ts
Labels: Type: Bug 🐛

#2712 chore(scripts): use lerna run for lint:types
  package.json
Labels: Topic: TypeScript 🤠

#2709 fix(system): set default useStyleConfig arguments
  .changeset/nice-tools-jump.md
  packages/system/src/use-style-config.ts
Labels: Type: Bug 🐛

#2741 fix(input): make focus outline take precedence over isInvalid outline
  .changeset/sour-cherries-unite.md
  packages/input/tests/__snapshots__/input.test.tsx.snap
  packages/number-input/tests/__snapshots__/number-input.test.tsx.snap
  packages/select/tests/__snapshots__/select.test.tsx.snap
  packages/textarea/tests/__snapshots__/text-area.test.tsx.snap
  packages/theme/src/components/input.ts
Labels: Type: Bug 🐛

#2759 fix(checkbox): fix themable parts list
  .changeset/stale-masks-stare.md
  packages/theme/src/components/checkbox.ts
Labels: Topic: Theming 🎨

#2797 chore(radio): omit invalid "defaultChecked" prop from RadioGroupProps
  packages/radio/src/radio-group.tsx
Labels: Topic: TypeScript 🤠

#2794 fix(list): enable ref forwarding for ListItem
  .changeset/short-fans-chew.md
  packages/layout/src/list.tsx
Labels: Type: Bug 🐛

#2812 docs(accordion): fix typo in README
  packages/accordion/README.md
Labels: Topic: Documentation 📚

#2834 feat(extend-theme): allow passing a base theme to customize
  .changeset/clean-balloons-pull.md
  packages/react/src/extend-theme.ts
Labels: Topic: Theming 🎨, Type: Feature 🚀

#2866 docs(tabs): fix omitted props
  website/pages/docs/components/tabs.mdx
Labels: Topic: Documentation 📚

#2875 fix(radio): allow useRadio to detect uncontrolled Radio
  .changeset/light-geckos-divide.md
  packages/radio/src/radio.tsx
  packages/radio/tests/behavior.test.tsx
Labels: Type: Bug 🐛

#2872 docs(guides): add Custom Fonts guide
  website/configs/guides-sidebar.json
  website/pages/guides/custom-fonts.mdx
Labels: Topic: Documentation 📚

#2873 chore(stalebot): make only "not stale" and high priority issues exempt
  .github/stale.yml
Labels: Topic: Repo Management :globe_with_meridians:

#2880 fix(pin-input): use valid autocomplete value
  .changeset/sharp-comics-tease.md
  packages/pin-input/src/use-pin-input.ts
Labels: Type: Bug 🐛

#2882 docs(tooltip): add note to wrap react-icons with span
  website/pages/docs/overlay/tooltip.mdx
Labels: Topic: Documentation 📚

#2876 refactor: deprecate defaultIsChecked props
  .changeset/late-colts-change.md
  packages/checkbox/src/use-checkbox.ts
  packages/radio/src/use-radio.ts
Labels: Type: Feature 🚀

#2906 docs: add Container import
  website/pages/docs/layout/container.mdx
Labels: Topic: Documentation 📚

#2888 Feat/modal animation
  .changeset/neat-plants-jog.md
  packages/modal/src/modal-transition.tsx
  packages/modal/src/modal.tsx
  packages/modal/stories/modal.stories.tsx
  website/pages/docs/overlay/modal.mdx
Labels: Type: Feature 🚀

#2919 fix(website): move /discord redirect to next-redirect
  website/next-redirect.js
  website/src/components/header.tsx
  website/vercel.json
Labels: Topic: Website 🖥

#2900 docs(guide): add react-table integration guide
  .changeset/four-hornets-joke.md
  website/configs/guides-sidebar.json
  website/pages/guides/integrations/with-react-table.mdx
  website/src/components/codeblock/react-live-scope.tsx
Labels: Topic: Documentation 📚

#2909 chore(modal): remove storybook multiple exports
  packages/modal/stories/index.stories.tsx
  packages/modal/stories/modal.stories.tsx
Labels: Topic: Storybook 📖
