Repository chakra-ui/chakra-ui, pull requests merged in 2021-11, with the labels that each got.

#5019 docs: accessibility fixes for Search button
  website/src/components/algolia-search.tsx
Labels: Topic: Accessibility (A11y) ♿️

#4989 fix(color-mode): fix colormode in system-view
  .changeset/wild-bikes-sneeze.md
  packages/color-mode/src/color-mode-provider.tsx
  packages/color-mode/src/color-mode-script.tsx
  packages/color-mode/src/color-mode.utils.ts
  packages/color-mode/test/color-mode-provider__browser.test.tsx
  packages/color-mode/test/color-mode-script.test.tsx
  packages/color-mode/test/testa.js
  website/pages/docs/features/color-mode.mdx
Labels: Topic: Color Mode 🌓, core team 🌼

#5081 fix: thumb does not move in case of stacked thumbs
  .changeset/happy-pants-tickle.md
  packages/slider/src/range-slider.tsx
  packages/slider/src/use-range-slider.ts
  packages/slider/tests/range-slider.test.tsx
Labels: Type: Bug 🐛, review needed 🔬

#5100 fix: prop-docs package
  .changeset/dull-weeks-drum.md
  .github/workflows/release.yml
  tooling/props-docs/package.json
  tooling/props-docs/src/build.ts
  website/src/components/props-table.tsx
  website/src/utils/convert-backticks-to-inline-code.tsx
Labels: core team 🌼

#5105 chore(color-mode): fix flaky color-mode-script test
  .changeset/mean-bikes-work.md
  packages/color-mode/test/color-mode-script.test.tsx
Labels: Topic: Color Mode 🌓, core team 🌼

#5123 feat: add flex gap
  .changeset/brown-rivers-switch.md
  packages/layout/src/flex.tsx
  packages/layout/stories/flex.stories.tsx
  packages/styled-system/src/config/flexbox.ts
Labels: Type: Feature 🚀, styled system 💅🏻

#5044 feat(popover): PopoverAnchor
  .changeset/twelve-trainers-eat.md
  packages/popover/src/popover.tsx
  packages/popover/src/use-popover.ts
  packages/popover/stories/popover.stories.tsx
Labels: review needed 🔬

#5133 docs: update storybook url to enable composition
  .changeset/long-dancers-vanish.md
  packages/react/package.json
Labels: Topic: Storybook 📖

#5144 chore(babel): silence babel loose warning
  .storybook/.babelrc
Labels: Topic: Storybook 📖
