Repository chakra-ui/chakra-ui, pull requests merged in 2021-02, with the labels that each got.

#3227 feat(chakra-theme): introduce type ChakraTheme
  .changeset/old-sheep-melt.md
  packages/react/src/extend-theme.ts
  packages/react/tests/extend-theme.test.tsx
  packages/styled-system/src/types.ts
  packages/theme/src/foundations/colors.ts
  packages/theme/src/foundations/index.ts
  packages/theme/src/foundations/radius.ts
  packages/theme/src/foundations/shadows.ts
  packages/theme/src/foundations/sizes.ts
  packages/theme/src/foundations/spacing.ts
  packages/theme/src/foundations/typography.ts
  packages/theme/src/foundations/z-index.ts
  packages/theme/src/index.ts
  packages/theme/src/theme.types.ts
Labels: Topic: TypeScript 🤠

#3241 docs(use-controllable): fix typo
  website/pages/docs/hooks/use-controllable.mdx
Labels: Topic: Documentation 📚

#3296 Fix: pin input last entry update fails to call onComplete
  .changeset/tiny-apples-wait.md
  packages/pin-input/src/use-pin-input.ts
  packages/pin-input/tests/pin-input.test.tsx
Labels: Type: Bug 🐛

#3297 docs(accordion): add button heading wrappers and note
  packages/accordion/stories/accordion.stories.tsx
  packages/accordion/tests/accordion.test.tsx
  website/pages/docs/disclosure/accordion.mdx
Labels: Topic: Accessibility (A11y) ♿️

#3300 fix: narrow theme types for defaultProps and ComponentMultiStyleConfig
  .changeset/tricky-beers-smell.md
  .github/workflows/release.yml
  packages/react/tests/extend-theme.test.tsx
  packages/theme/src/theme.types.ts
Labels: Type: Bug 🐛

#3310 fix: fixed Benjamin Carlson's resource URL
  website/configs/resources.json
Labels: Topic: Documentation 📚

#3306 fix: allow custom breakpoint names in ResponsiveObject
  .changeset/big-cherries-wash.md
  packages/styled-system/src/utils/types.ts
  packages/styled-system/tests/css-type.test.ts
Labels: Topic: TypeScript 🤠

#3309 fix: cli tokens command ignores TS errors in theme file
  .changeset/red-mayflies-reflect.md
  tooling/cli/bin/tsconfig.json
Labels: Type: Bug 🐛

#3366 fix: remove default theme type cast
  .changeset/soft-knives-hide.md
  .changeset/sweet-otters-arrive.md
  packages/react/src/extend-theme.ts
  packages/react/tests/extend-theme.test.tsx
  packages/theme/src/index.ts
  packages/theme/tests/theme.test.ts
Labels: Topic: TypeScript 🤠

#3395 docs: Fix minor typos in comparison.mdx
  website/pages/docs/comparison.mdx
Labels: Topic: Documentation 📚

#3399 docs: align theming/theme with default theme (fontSizes, lineHeights, sizes, radii, borderRadius)
  website/pages/docs/theming/theme.mdx
Labels: Topic: Documentation 📚

#3398 docs: update default theme hex color value
  website/pages/docs/theming/theme.mdx
Labels: Topic: Documentation 📚

#3417 docs: Link to Themera for generating custom themes
  website/pages/docs/theming/theme.mdx
Labels: Topic: Documentation 📚
