Repository chakra-ui/chakra-ui, pull requests merged in 2021-06, with the labels that each got.

#4067 ✨ Support generating token type definitions from theme packages
  .changeset/soft-hairs-happen.md
  tooling/cli/README.md
  tooling/cli/src/scripts/read-theme-file.worker.ts
  website/pages/docs/theming/advanced.mdx
Labels: CLI ⚙️, Type: Feature 🚀

#4103 fix(style): remove outline transitions
  .changeset/short-items-shake.md
  packages/accordion/src/accordion.tsx
  packages/button/src/button.tsx
  packages/checkbox/src/checkbox.tsx
  packages/control-box/src/control-box.tsx
  packages/menu/src/menu.tsx
  packages/modal/stories/modal.stories.tsx
  packages/number-input/src/number-input.tsx
  packages/progress/src/circular-progress.tsx
  packages/tabs/src/use-tabs.ts
  packages/tag/src/tag.tsx
  packages/theme/src/components/accordion.ts
  packages/theme/src/components/breadcrumb.ts
  packages/theme/src/components/button.ts
  packages/theme/src/components/checkbox.ts
  packages/theme/src/components/close-button.ts
  packages/theme/src/components/editable.ts
  packages/theme/src/components/form-label.ts
  packages/theme/src/components/input.ts
  packages/theme/src/components/link.ts
  packages/theme/src/components/menu.ts
  packages/theme/src/components/progress.ts
  packages/theme/src/components/slider.ts
  packages/theme/src/components/switch.ts
  packages/theme/src/components/tabs.ts
  packages/theme/src/components/tag.ts
  packages/theme/src/styles.ts
  website/src/components/search.styles.tsx
Labels: Type: Bug 🐛

#4145 docs(toast): add update toasts example
  website/pages/docs/feedback/toast.mdx
Labels: Topic: Documentation 📚

#4069 fix: (proposition) fixing the Collapse transition unmountOnExit issue
  .changeset/rare-bulldogs-roll.md
  package.json
  packages/transition/src/collapse.tsx
  packages/transition/stories/collapse.stories.tsx
  yarn.lock
Labels: Critical Review Needed: Don't merge 🛑

#4144 docs(404): new 404 page
  website/pages/404.tsx
Labels: Topic: Website 🖥

#4150 docs(toast): add required theme arg note for createStandaloneToast
  website/pages/docs/feedback/toast.mdx
Labels: Topic: Documentation 📚

#4176 docs: fix minor numeric typo
  website/pages/docs/features/responsive-styles.mdx
Labels: Topic: Documentation 📚

#4208 fix(website): update Chakra discord links
  README.md
  website/configs/site-config.ts
  website/next-redirect.js
  website/src/components/discord-strip.tsx
Labels: Topic: Website 🖥

#4274 chore(stalebot): target only issues awaiting a response/reproduction
  .github/stale.yml
Labels: Topic: Repo Management :globe_with_meridians:

#4277 chore: use GitHub issues forms for bug report and feature request
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: Topic: Repo Management :globe_with_meridians:
