Repository chakra-ui/chakra-ui, pull requests merged in 2021-03, with the labels that each got.

#3486 fix(select): add baseStyle bg for optgroup element
  .changeset/silly-mice-repair.md
  packages/theme/src/components/select.ts
Labels: Type: Bug 🐛

#3439 fix: provide proper typings for ThemeOverride.components
  .changeset/orange-tools-smell.md
  packages/react/tests/extend-theme.test.tsx
  packages/theme/src/theme.types.ts
Labels: Topic: TypeScript 🤠

#2895 fix(slider): call onChangeEnd even if value doesn't change
  .changeset/perfect-melons-serve.md
  packages/slider/src/use-slider.ts
Labels: Type: Bug 🐛

#3438 fix: extend theme type with breakpoints
  .changeset/rotten-panthers-worry.md
  packages/react/src/extend-theme.ts
Labels: Topic: TypeScript 🤠

#3510 docs: extract hook props for docs
  .changeset/poor-numbers-burn.md
  tooling/props-docs/src/build.ts
Labels: Topic: Documentation 📚

#3563 docs: updated exisiting dark mode comparison for tailwindCSS
  website/pages/docs/comparison.mdx
Labels: Topic: Documentation 📚

#3573 chore: update bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Topic: Repo Management :globe_with_meridians:

#3529 feat: include text/layer styles in theme types
  .changeset/fair-zoos-rule.md
  packages/styled-system/src/config/others.ts
  packages/styled-system/src/theming.types.ts
  packages/system/src/system.types.tsx
  tooling/cli/src/command/tokens/config.ts
  tooling/cli/src/command/tokens/create-theme-typings-interface.ts
  tooling/cli/src/command/tokens/extract-property-keys.ts
  tooling/cli/test/extract-keys.test.ts
  tooling/cli/test/theme-typings.test.ts
Labels: Topic: TypeScript 🤠, Type: Feature 🚀

#3481 chore: speed up start
  package.json
  packages/accordion/index.ts
  packages/alert/index.ts
  packages/avatar/index.ts
  packages/breadcrumb/index.ts
  packages/button/index.ts
  packages/checkbox/index.ts
  packages/clickable/index.ts
  packages/close-button/index.ts
  packages/color-mode/index.ts
  packages/control-box/index.ts
  packages/counter/index.ts
  packages/css-reset/index.ts
  packages/descendant/index.ts
  packages/editable/index.ts
  packages/focus-lock/index.ts
  packages/form-control/index.ts
  packages/hooks/index.ts
  packages/icon/index.ts
  packages/icons/index.ts
  packages/image/index.ts
  packages/input/index.ts
  packages/layout/index.ts
  packages/live-region/index.ts
  packages/media-query/index.ts
  packages/menu/index.ts
  packages/modal/index.ts
  packages/number-input/index.ts
  packages/pin-input/index.ts
  packages/popover/index.ts
  packages/popper/index.ts
  packages/portal/index.ts
  packages/progress/index.ts
  packages/radio/index.ts
  packages/react/index.ts
  packages/select/index.ts
  packages/skeleton/index.ts
  packages/skip-nav/index.ts
  packages/slider/index.ts
  packages/spinner/index.ts
  packages/stat/index.ts
  packages/styled-system/index.ts
  packages/switch/index.ts
  packages/system/index.ts
  packages/table/index.ts
  packages/tabs/index.ts
  packages/tag/index.ts
  packages/test-utils/index.ts
  packages/textarea/index.ts
  packages/theme-tools/index.ts
  packages/theme/index.ts
  packages/toast/index.ts
  packages/tooltip/index.ts
  packages/transition/index.ts
  packages/utils/index.ts
  packages/visually-hidden/index.ts
  plop-templates/component-pkg/index.ts.hbs
Labels: Critical Review Needed: Don't merge 🛑, Topic: Development :computer:

#3615 fix: styled system css and css vars
  .changeset/olive-walls-promise.md
  packages/styled-system/src/config/others.ts
  packages/styled-system/src/css-var.ts
  packages/styled-system/src/css.ts
  packages/styled-system/src/types.ts
  packages/styled-system/stories/css.stories.tsx
  packages/styled-system/tests/css-var.test.ts
  packages/styled-system/tests/text-styles.test.ts
  packages/system/tests/style-resolver.test.ts
Labels: core team 🌼

#3621 fix: CLI exits unexpectedly on warnings
  .changeset/loud-rivers-listen.md
  tooling/cli/src/command/tokens/index.ts
  tooling/cli/src/scripts/read-theme-file.worker.ts
Labels: Topic: Tooling 🛠

#3623 feat: add support for framer-motion v4
  .changeset/cyan-worms-change.md
  .changeset/funny-radios-teach.md
  .changeset/yellow-readers-know.md
  README.md
  examples/create-react-app/package.json
  examples/gatsby/package.json
  examples/next-js/package.json
  examples/nextjs-typescript/package.json
  package.json
  packages/checkbox/package.json
  packages/checkbox/src/checkbox-icon.tsx
  packages/menu/package.json
  packages/menu/src/menu.tsx
  packages/modal/package.json
  packages/popover/package.json
  packages/react/package.json
  packages/toast/package.json
  packages/tooltip/package.json
  packages/transition/package.json
  packages/transition/src/collapse.tsx
  tooling/cra-template-typescript/template.json
  tooling/cra-template/template.json
  website/pages/docs/getting-started.mdx
  website/pages/docs/migration.mdx
  yarn.lock
Labels: Type: Dependency 🔗, Type: Feature 🚀

#3622 feat: export type ThemeComponentProps with theme property
  .changeset/wicked-apes-wink.md
  packages/theme/src/theme.types.ts
Labels: Topic: TypeScript 🤠

#3614 docs: add Next JS TypeScript starter link
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
Labels: Topic: Documentation 📚

#3678 fix: improve switch accessibility
  .changeset/giant-rules-switch.md
  .changeset/gorgeous-flowers-impress.md
  .changeset/pink-timers-explode.md
  .changeset/witty-ears-boil.md
  packages/checkbox/src/checkbox.tsx
  packages/checkbox/src/use-checkbox.ts
  packages/styled-system/src/css.ts
  packages/switch/README.md
  packages/switch/src/switch.tsx
  packages/theme/src/components/stat.ts
  packages/theme/src/components/switch.ts
  packages/theme/src/components/table.ts
Labels: Topic: Accessibility (A11y) ♿️, core team 🌼

#3707 docs(modal): fix scrolling example Lorem usage
  website/pages/docs/overlay/modal.mdx
Labels: Topic: Documentation 📚
