Repository chakra-ui/chakra-ui, pull requests merged in 2021-07, with the labels that each got.

#4294 docs: fixed broken divider source link
  website/pages/docs/data-display/divider.mdx
Labels: Topic: Documentation 📚

#4368 fix: make grid props type definitions reflect current implementation
  .changeset/rare-experts-beg.md
  packages/styled-system/src/config/grid.ts
Labels: Topic: TypeScript 🤠

#4350 docs: Update drawer.mdx
  website/pages/docs/overlay/drawer.mdx
Labels: Topic: Documentation 📚

#4317 feat: enable root element to be themed
  .changeset/sharp-cooks-clap.md
  packages/form-control/src/form-control.tsx
  packages/theme/src/components/form.ts
Labels: Topic: Theming 🎨

#4314 Docs/daily workflow
  .github/workflows/daily.yml
  package.json
Labels: Topic: Build and Workflow ↩️, Topic: Website 🖥

#4313 docs(discordbanner): changes the discord banner to match the new logo…
  website/src/components/discord-strip.tsx
  website/src/components/docs/discord-logo.tsx
Labels: Topic: Website 🖥

#4196 Put sandbox example on wiki page
  website/pages/guides/integrations/with-hook-form.mdx
Labels: Topic: Website 🖥
