Repository chakra-ui/chakra-ui, pull requests merged in 2021-05, with the labels that each got.

#3930 feat(utils): add return value typings for `pipe`
  .changeset/kind-rocks-kick.md
  packages/utils/src/function.ts
Labels: Topic: TypeScript 🤠

#3976 chore: speed up test runs
  .github/workflows/pr.yml
  .github/workflows/release.yml
  jest.config.js
  package.json
  packages/styled-system/tests/interpolation.test.ts
Labels: Topic: Build and Workflow ↩️

#3997 feat: ring and filter style props
  .changeset/eleven-numbers-battle.md
  .changeset/friendly-cobras-brush.md
  packages/styled-system/src/config/background.ts
  packages/styled-system/src/config/border.ts
  packages/styled-system/src/config/color.ts
  packages/styled-system/src/config/effect.ts
  packages/styled-system/src/config/filter.ts
  packages/styled-system/src/config/flexbox.ts
  packages/styled-system/src/config/grid.ts
  packages/styled-system/src/config/index.ts
  packages/styled-system/src/config/interactivity.ts
  packages/styled-system/src/config/layout.ts
  packages/styled-system/src/config/list.ts
  packages/styled-system/src/config/others.ts
  packages/styled-system/src/config/outline.ts
  packages/styled-system/src/config/position.ts
  packages/styled-system/src/config/ring.ts
  packages/styled-system/src/config/shadow.ts
  packages/styled-system/src/config/space.ts
  packages/styled-system/src/config/text-decoration.ts
  packages/styled-system/src/config/transform.ts
  packages/styled-system/src/config/transition.ts
  packages/styled-system/src/config/typography.ts
  packages/styled-system/src/create-theme-vars/theme-tokens.ts
  packages/styled-system/src/create-theme-vars/to-css-var.ts
  packages/styled-system/src/create-theme-vars/transform-template.ts
  packages/styled-system/src/css.ts
  packages/styled-system/src/index.ts
  packages/styled-system/src/pseudos.ts
  packages/styled-system/src/system.ts
  packages/styled-system/src/system.types.ts
  packages/styled-system/src/utils/create-transform.ts
  packages/styled-system/src/utils/expand-responsive.ts
  packages/styled-system/src/utils/index.ts
  packages/styled-system/src/utils/parse-gradient.ts
  packages/styled-system/src/utils/prop-config.ts
  packages/styled-system/src/utils/templates.ts
  packages/styled-system/src/utils/transform-functions.ts
  packages/styled-system/src/utils/types.ts
  packages/styled-system/stories/css.stories.tsx
  packages/styled-system/tests/css-type.test.ts
  packages/styled-system/tests/css-var.test.ts
  packages/theme/src/foundations/blur.ts
  packages/theme/src/foundations/index.ts
Labels: Type: Feature 🚀

#4078 feat: add `/docs` redirect to getting started page
  website/next-redirect.js
Labels: Topic: Website 🖥

#4091 docs: added design vs dev challenge video link in resources
  website/configs/resources.json
Labels: Topic: Documentation 📚

#4084 docs: chakra and ant design comparison
  website/pages/docs/comparison.mdx
Labels: Topic: Documentation 📚

#4051 docs(with-framer): Simplify Typescript example for framer-motion
  website/pages/guides/integrations/with-framer.mdx
Labels: Status: Awaiting Response ⏳, Topic: Documentation 📚

#4113 docs: removed extra dot in checkbox onChange desc
  packages/checkbox/src/use-checkbox.ts
Labels: Topic: Documentation 📚

#4107 Update color-mode.mdx
  website/pages/docs/features/color-mode.mdx
Labels: Topic: Documentation 📚
