Repository chakra-ui/chakra-ui, pull requests merged in 2021-01, with the labels that each got.

#2926 docs(motion-box): update motion box guide
  website/pages/guides/integrations/with-framer.mdx
Labels: Topic: Documentation 📚, Topic: Integrations :infinity:

#2930 fix(deprecation): deprecate isFullWidth on Input, NumberInput, Radio,…
  packages/input/src/input.tsx
  packages/number-input/src/number-input.tsx
  packages/radio/src/radio.tsx
  packages/select/src/select.tsx
  packages/textarea/src/textarea.tsx
Labels: Topic: Component API ⚙️

#2927 fix document using <input type="phone">
  .changeset/spicy-goats-rule.md
  examples/gatsby/src/pages/index.js
  examples/next-js/pages/index.js
  packages/input/README.md
  packages/input/stories/input.stories.tsx
  website/pages/docs/form/input.mdx
Labels: Topic: Documentation 📚

#2908 docs: update tab accessibility docs
  .changeset/smart-timers-fail.md
  package.json
  packages/tabs/src/use-tabs.ts
  website/pages/docs/components/tabs.mdx
  yarn.lock
Labels: Topic: Accessibility (A11y) ♿️

#2929 docs: update color-mode.mdx
  website/pages/docs/features/color-mode.mdx
Labels: Topic: Documentation 📚

#2753 fix: typescript autocomplete
  .changeset/brown-cherries-collect.md
  packages/modal/src/modal-transition.tsx
  packages/modal/src/modal.tsx
  packages/system/src/forward-ref.tsx
  packages/system/src/system.ts
  packages/system/src/system.types.tsx
  packages/system/tests/as-prop.test.tsx
  packages/transition/src/fade.tsx
Labels: Topic: TypeScript 🤠

#2911 docs(use-token): replace gradient example with boxShadow example
  .changeset/sweet-cherries-breathe.md
  website/pages/docs/hooks/use-token.mdx
Labels: Topic: Documentation 📚

#2751 feat: add "xs" size to Input and all related components
  .changeset/bright-drinks-run.md
  packages/input/stories/input.stories.tsx
  packages/input/tests/__snapshots__/input.test.tsx.snap
  packages/number-input/stories/number-input.stories.tsx
  packages/number-input/tests/__snapshots__/number-input.test.tsx.snap
  packages/pin-input/stories/pin-input.stories.tsx
  packages/select/src/select.tsx
  packages/select/stories/select.stories.tsx
  packages/textarea/stories/textarea.stories.tsx
  packages/theme/package.json
  packages/theme/src/components/input.ts
  packages/theme/src/components/number-input.ts
  packages/theme/src/components/pin-input.ts
  packages/theme/src/components/select.ts
  packages/theme/src/components/textarea.ts
  website/pages/docs/form/input.mdx
  website/pages/docs/form/number-input.mdx
  website/pages/docs/form/pin-input.mdx
  website/pages/docs/form/select.mdx
Labels: Topic: Theming 🎨

#3015 fix: un-break broken 1.1.3 release
  .changeset/mighty-ghosts-ring.md
  .changeset/two-pears-sneeze.md
  .changeset/wild-mails-do.md
  packages/hooks/src/index.ts
  packages/hooks/src/use-event-callback.ts
  packages/hooks/src/use-latest-ref.ts
  packages/hooks/src/use-mouse-down-ref.ts
Labels: Priority: High 🚨

#3005 fix(docs): format size and variant values as TS types
  .changeset/tasty-singers-design.md
  website/src/components/props-table.tsx
Labels: Topic: Documentation 📚

#3025 chore(docs): split installation codeblocks to allow easier copying
  website/pages/docs/getting-started.mdx
Labels: Topic: Documentation 📚

#2946 fix(progress): allow overriding borderRadius in theme
  .changeset/brave-ties-flow.md
  packages/progress/src/progress.tsx
  packages/progress/stories/progress.stories.tsx
Labels: Topic: Theming 🎨

#3019 docs: change the Global import
  website/pages/guides/with-nextjs-font-files.mdx
Labels: Topic: Documentation 📚

#3056 fix(use-event-listener): restore listener fn
  .changeset/orange-boats-pretend.md
  packages/hooks/src/use-event-listener.ts
Labels: Type: Bug 🐛

#3061 docs(progress): correct description about thickness prop
  packages/progress/src/circular-progress.tsx
  website/pages/docs/feedback/circular-progress.mdx
Labels: Topic: Documentation 📚

#3064 docs(color-mode): Fix Next _document.js example
  website/pages/docs/features/color-mode.mdx
Labels: Topic: Documentation 📚

#3036 feat(docs): display "not implemented" note for size and variant where appropriate
  .changeset/friendly-parents-guess.md
  website/src/components/props-table.tsx
Labels: Topic: Documentation 📚

#3095 feat(pin-input): add otp flag to PinInput
  .changeset/four-ways-visit.md
  packages/pin-input/src/use-pin-input.ts
  packages/pin-input/tests/pin-input.test.tsx
  website/pages/docs/form/pin-input.mdx
Labels: Topic: Component API ⚙️, Type: Feature 🚀

#3109 docs(theme): add missing fontWeights
  website/pages/docs/theming/theme.mdx
Labels: Topic: Documentation 📚

#3130 docs(table): add Tfoot import and uses
  website/pages/docs/data-display/table.mdx
Labels: Topic: Documentation 📚

#3129 fix(select): allow Select.icon component theme color to be applied
  .changeset/odd-cobras-fix.md
  packages/select/src/select.tsx
Labels: Type: Bug 🐛

#3133 fix: useColorModeValue to default to light mode first, dark only if set
  .changeset/shaggy-seahorses-poke.md
  packages/color-mode/src/color-mode-provider.tsx
Labels: Type: Bug 🐛

#3155 fix(docs): correct capitalization of rightIcon
  .changeset/wild-pandas-suffer.md
  website/pages/docs/form/button.mdx
Labels: Topic: Documentation 📚

#3158 chore(ci): upgrade actions/cache to v2
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: Topic: Build and Workflow ↩️

#3150 fix(extend-theme): allow nested theme colors
  .changeset/weak-wombats-shake.md
  packages/react/src/extend-theme.ts
  packages/react/tests/extend-theme.test.tsx
Labels: Topic: TypeScript 🤠

#3179 fix(number-input): always cast counter.value
  packages/number-input/src/use-number-input.ts
  packages/number-input/tests/number-input.test.tsx
Labels: Type: Bug 🐛

#3180 fix(checkbox): call group.onChange only once
  .changeset/slimy-birds-melt.md
  packages/checkbox/src/checkbox.tsx
  packages/checkbox/tests/checkbox.test.tsx
Labels: Type: Bug 🐛

#2594 chore(ci): add CRA templates build to pr workflow
  .github/workflows/pr.yml
  package.json
  scripts/build-templates.ts
Labels: Topic: Build and Workflow ↩️

#3200 fix(theme): align link button to baseline
  .changeset/tidy-berries-promise.md
  packages/theme/src/components/button.ts
Labels: Topic: Design and UX ✍️

#3221 fix: loosen colorScheme type
  .changeset/slow-chicken-shave.md
  packages/system/src/system.types.tsx
Labels: Topic: TypeScript 🤠, Type: Bug 🐛

#3222 chore: bump cli package to publish previous package
  .changeset/unlucky-onions-sin.md
  tooling/cli/package.json
  website/pages/docs/theming/advanced.mdx
Labels: Topic: Release Management :package:

#3225 docs: update cli install instructions
  website/pages/docs/theming/advanced.mdx
Labels: Topic: Documentation 📚

#3229 docs(tooltip): remove shouldWrapChildren prop from examples
  website/pages/docs/overlay/tooltip.mdx
Labels: Topic: Documentation 📚
