Repository chakra-ui/chakra-ui, pull requests merged in 2021-04, with the labels that each got.

#3691 docs(guides): update font installation instructions
  website/configs/guides-sidebar.json
  website/pages/guides/custom-fonts.mdx
  website/pages/guides/using-fonts.mdx
  website/pages/guides/with-nextjs-font-files.mdx
Labels: Topic: Documentation 📚

#3715 fix: forward transitive react-dom peer dependency
  .changeset/perfect-colts-fry.md
  .changeset/slow-lies-grab.md
  packages/modal/package.json
  packages/radio/src/use-radio.ts
  packages/react/package.json
  packages/tooltip/package.json
Labels: Type: Dependency 🔗

#3679 docs(component-style): default Chakra component + custom component styling
  website/pages/docs/theming/component-style.mdx
  website/public/button-spec.png
  website/public/card-spec.png
  website/public/eric.jpg
Labels: Topic: Documentation 📚

#3779 fix(extend-theme): use DeepPartial to fix TS override error
  .changeset/chilly-apples-lick.md
  packages/react/src/extend-theme.ts
Labels: Topic: Theming 🎨, Topic: TypeScript 🤠

#3805 feat(system): allow passing custom props to useStyleConfig
  .changeset/orange-pens-destroy.md
  packages/system/src/use-style-config.ts
Labels: Topic: TypeScript 🤠

#3807 docs(toast): add note to call useToast below ChakraProvider
  website/pages/docs/feedback/toast.mdx
Labels: Topic: Documentation 📚

#3802 feat: adding youtube links in footer and navigation
  website/configs/site-config.ts
  website/src/components/footer.tsx
  website/src/components/header.tsx
Labels: Topic: Website 🖥

#3806 fix(modal): calc height correctly on iOS
  .changeset/violet-chicken-fry.md
  packages/modal/src/modal.tsx
  packages/theme/src/components/modal.ts
Labels: Topic: Design and UX ✍️

#3793 feat: embedded getting started video in docs
  website/package.json
  website/pages/docs/getting-started.mdx
  website/src/components/mdx-components.tsx
  yarn.lock
Labels: Topic: Documentation 📚, Type: Feature 🚀

#3833 docs (global styles) Correction of example config
  website/pages/docs/features/global-styles.mdx
Labels: Topic: Documentation 📚

#3839 feat(tabs): make new isLazy behavior toggleable via unmountHiddenPanels prop
  .changeset/perfect-beans-raise.md
  packages/tabs/src/use-tabs.ts
  packages/tabs/src/utils.ts
  packages/tabs/tests/tabs.test.tsx
  packages/tabs/tests/utils.test.ts
Labels: Type: Bug 🐛

#3747 chore(storybook): upgrade to 6.2
  .storybook/.babelrc
  package.json
  yarn.lock
Labels: Topic: Storybook 📖

#3875 fix(button): #3859 fix button type as undefined
  .changeset/lovely-dancers-guess.md
  packages/button/src/button.tsx
  packages/button/tests/button.test.tsx
Labels: Type: Bug 🐛

#3511 feat: add theme extension withDefaultColorScheme
  .changeset/tiny-hornets-dress.md
  .changeset/young-fishes-tap.md
  packages/react/src/extend-theme.ts
  packages/react/src/index.tsx
  packages/react/src/theme-extensions/index.ts
  packages/react/src/theme-extensions/with-default-color-scheme.ts
  packages/react/src/theme-extensions/with-default-props.ts
  packages/react/src/theme-extensions/with-default-size.ts
  packages/react/src/theme-extensions/with-default-variant.ts
  packages/react/tests/theme-extension.test.tsx
  packages/react/tests/with-default-color-scheme.test.tsx
  packages/react/tests/with-default-props.test.tsx
  packages/react/tests/with-default-size.test.tsx
  packages/react/tests/with-default-variant.test.tsx
  packages/theme/src/index.ts
  packages/theme/src/utils.ts
  packages/theme/tests/theme.test.ts
  packages/utils/src/assertion.ts
  website/pages/docs/theming/customize-theme.mdx
Labels: Topic: TypeScript 🤠, Type: Feature 🚀

#3864 perf: improve descendant management
  .changeset/four-wasps-reflect.md
  .changeset/funny-peas-smell.md
  .changeset/gentle-rabbits-guess.md
  .changeset/lovely-pots-melt.md
  .changeset/old-grapes-pretend.md
  .changeset/proud-queens-join.md
  packages/accordion/src/accordion.tsx
  packages/accordion/src/use-accordion.ts
  packages/accordion/stories/accordion.stories.tsx
  packages/descendant/README.md
  packages/descendant/package.json
  packages/descendant/src/descendant.ts
  packages/descendant/src/index.ts
  packages/descendant/src/use-descendant.ts
  packages/descendant/src/utils.ts
  packages/descendant/stories/async.stories.tsx
  packages/descendant/stories/number-input.stories.tsx
  packages/descendant/stories/use-descendant.stories.tsx
  packages/menu/src/menu.tsx
  packages/menu/src/use-menu.ts
  packages/menu/stories/menu.stories.tsx
  packages/pin-input/src/pin-input.tsx
  packages/pin-input/src/use-pin-input.ts
  packages/pin-input/stories/pin-input.stories.tsx
  packages/pin-input/tests/pin-input.test.tsx
  packages/react-utils/src/context.ts
  packages/react-utils/src/refs.ts
  packages/react/CHANGELOG.md
  packages/styled-system/CHANGELOG.md
  packages/tabs/src/tabs.tsx
  packages/tabs/src/use-tabs.ts
  packages/tabs/stories/tabs.stories.tsx
Labels: Topic: Performance
