Repository chakra-ui/chakra-ui, pull requests merged in 2022-04, with the labels that each got.

#5618 feat(form-control): add optional indicator for `FormLabel`
  .changeset/sharp-crews-wave.md
  packages/form-control/src/form-label.tsx
  packages/form-control/tests/form-control.test.tsx
Labels: Topic: Component API ⚙️

#5797 feat(react-18-toast): toast with React Portal implementation
  .changeset/new-rivers-fail.md
  packages/react/src/chakra-provider.tsx
  packages/toast/package.json
  packages/toast/src/create-standalone-toast.tsx
  packages/toast/src/index.ts
  packages/toast/src/toast-manager.tsx
  packages/toast/src/toast.class.tsx
  packages/toast/src/toast.component.tsx
  packages/toast/src/toast.placement.ts
  packages/toast/src/toast.provider.tsx
  packages/toast/src/toast.tsx
  packages/toast/src/toast.types.ts
  packages/toast/src/use-toast-provider.tsx
  packages/toast/src/use-toast.tsx
  packages/toast/stories/toast.stories.tsx
  packages/toast/test/standalone-toast.test.tsx
  packages/toast/test/use-toast.test.tsx
Labels: Breaking Change :hammer:, React 18 ⚛️

#5828 chore: remove deprecations
  .changeset/lovely-donkeys-heal.md
  packages/button/src/button.tsx
  packages/button/src/icon-button.tsx
  packages/button/tests/button.test.tsx
  packages/checkbox/src/use-checkbox.ts
  packages/color-mode/src/color-mode-script.tsx
  packages/color-mode/src/color-mode.utils.ts
  packages/hooks/src/index.ts
  packages/hooks/src/use-event-callback.ts
  packages/hooks/src/use-mouse-down-ref.ts
  packages/input/src/input.tsx
  packages/layout/src/grid.tsx
  packages/media-query/tests/matchmedia-mock-plus.ts
  packages/number-input/src/number-input.tsx
  packages/radio/src/radio.tsx
  packages/radio/src/use-radio.ts
  packages/select/src/select.tsx
  packages/styled-system/src/config/layout.ts
  packages/styled-system/src/config/typography.ts
  packages/textarea/src/textarea.tsx
  packages/theme/src/foundations/colors.ts
  packages/theme/src/foundations/index.ts
  packages/theme/src/foundations/radius.ts
  packages/theme/src/foundations/shadows.ts
  packages/theme/src/foundations/sizes.ts
  packages/theme/src/foundations/spacing.ts
  packages/theme/src/foundations/typography.ts
  packages/theme/src/foundations/z-index.ts
  packages/theme/src/index.ts
Labels: Breaking Change :hammer:

#5851 test: remove deprecations
  packages/checkbox/tests/checkbox.test.tsx
  packages/color-mode/test/color-mode-script.test.tsx
  packages/radio/tests/behavior.test.tsx
Labels: React 18 ⚛️

#5850 chore(toast): remove dependency to @reach-ui/alert
  .changeset/forty-plums-attend.md
  packages/toast/package.json
  packages/toast/src/index.ts
  packages/toast/src/toast.component.tsx
  packages/toast/src/toast.provider.tsx
  packages/toast/src/toast.types.ts
  packages/toast/stories/toast.stories.tsx
  yarn.lock
Labels: React 18 ⚛️

#5852 ci: run PR workflow on next branch as target
  .github/workflows/pr.yml
Labels: Topic: Repo Management :globe_with_meridians:

#5310 feat: add support for async toast
  examples/nextjs-typescript/package.json
  packages/alert/package.json
  packages/alert/src/alert.tsx
  packages/alert/stories/alert.stories.tsx
  packages/anatomy/src/index.ts
  packages/color-mode/test/color-mode-provider.test.tsx
  packages/color-mode/test/color-mode-provider__browser.test.tsx
  packages/media-query/package.json
  packages/skeleton/package.json
  packages/theme/src/components/alert.ts
  packages/toast/src/toast.types.ts
  packages/toast/src/use-toast.tsx
  packages/toast/stories/toast.stories.tsx
  packages/toast/test/use-toast.test.tsx
  packages/utils/src/function.ts
  yarn.lock
Labels: Type: Feature 🚀

#5882 chore: bump react & react-dom peer deps
  .changeset/thirty-trains-brush.md
  packages/accordion/package.json
  packages/alert/package.json
  packages/avatar/package.json
  packages/breadcrumb/package.json
  packages/button/package.json
  packages/checkbox/package.json
  packages/clickable/package.json
  packages/close-button/package.json
  packages/color-mode/package.json
  packages/control-box/package.json
  packages/counter/package.json
  packages/css-reset/package.json
  packages/descendant/package.json
  packages/editable/package.json
  packages/env/package.json
  packages/focus-lock/package.json
  packages/form-control/package.json
  packages/hooks/package.json
  packages/icon/package.json
  packages/icons/package.json
  packages/image/package.json
  packages/input/package.json
  packages/layout/package.json
  packages/live-region/package.json
  packages/media-query/package.json
  packages/menu/package.json
  packages/modal/package.json
  packages/number-input/package.json
  packages/pin-input/package.json
  packages/popover/package.json
  packages/popper/package.json
  packages/portal/package.json
  packages/progress/package.json
  packages/provider/package.json
  packages/radio/package.json
  packages/react-utils/package.json
  packages/react/package.json
  packages/select/package.json
  packages/skeleton/package.json
  packages/skip-nav/package.json
  packages/slider/package.json
  packages/spinner/package.json
  packages/stat/package.json
  packages/switch/package.json
  packages/system/package.json
  packages/table/package.json
  packages/tabs/package.json
  packages/tag/package.json
  packages/textarea/package.json
  packages/toast/package.json
  packages/tooltip/package.json
  packages/transition/package.json
  packages/visually-hidden/package.json
  tooling/cra-template-typescript/template/src/index.tsx
  tooling/cra-template/template/src/index.js
  tooling/test-utils/package.json
  yarn.lock
Labels: Breaking Change :hammer:, React 18 ⚛️
