Repository chakra-ui/chakra-ui, pull requests merged in 2022-01, with the labels that each got.

#5362 fix: index issue with range slider
  .changeset/popular-monkeys-matter.md
  packages/slider/src/use-range-slider.ts
Labels: review needed 🔬

#5316 feat(styled-system): introduce semantic tokens
  .changeset/dull-keys-occur.md
  .changeset/purple-yaks-type.md
  packages/color-mode/src/color-mode-script.tsx
  packages/color-mode/src/color-mode.utils.ts
  packages/color-mode/test/color-mode-script.test.tsx
  packages/color-mode/test/testa.js
  packages/layout/stories/text.stories.tsx
  packages/styled-system/src/create-theme-vars/create-theme-vars.ts
  packages/styled-system/src/create-theme-vars/flatten-tokens.ts
  packages/styled-system/src/create-theme-vars/index.ts
  packages/styled-system/src/create-theme-vars/theme-tokens.ts
  packages/styled-system/src/create-theme-vars/to-css-var.ts
  packages/styled-system/src/index.ts
  packages/styled-system/tests/css-var.test.ts
  packages/theme/src/theme.types.ts
  packages/utils/src/flatten.ts
  packages/utils/src/index.ts
  packages/utils/tests/flatten.test.ts
Labels: Type: Feature 🚀, styled system 💅🏻

#5419 feat: add entrypoints for theme parts
  .changeset/tender-forks-grow.md
  packages/theme/components/package.json
  packages/theme/foundations/blur/package.json
  packages/theme/foundations/borders/package.json
  packages/theme/foundations/breakpoints/package.json
  packages/theme/foundations/colors/package.json
  packages/theme/foundations/package.json
  packages/theme/foundations/radius/package.json
  packages/theme/foundations/shadows/package.json
  packages/theme/foundations/sizes/package.json
  packages/theme/foundations/spacing/package.json
  packages/theme/foundations/transition/package.json
  packages/theme/foundations/typography/package.json
  packages/theme/foundations/z-index/package.json
  packages/theme/package.json
Labels: core team 🌼

#4982 fix: number input
  .changeset/big-ways-attack.md
  .changeset/thick-pumpkins-approve.md
  packages/number-input/src/use-attr-observer.ts
  packages/number-input/src/use-number-input.ts
  packages/number-input/src/use-spinner.ts
  packages/number-input/src/utils.ts
  packages/number-input/tests/custom-format.test.tsx
  packages/number-input/tests/number-input.test.tsx
Labels: Topic: Component API ⚙️, core team 🌼

#5443 ci: skip pr publish step if actor is not org member
  .github/workflows/pr.yml
Labels: Topic: Build and Workflow ↩️

#5442 fix: lazy popover and menu unmounting
  .changeset/happy-rings-move.md
  .changeset/itchy-boxes-notice.md
  .gitignore
  package.json
  packages/hooks/package.json
  packages/hooks/src/index.ts
  packages/hooks/src/use-animation-state.ts
  packages/hooks/use-animation-state/package.json
  packages/menu/src/menu.tsx
  packages/menu/src/use-menu.ts
  packages/popover/src/popover.tsx
  packages/popover/src/use-popover.ts
Labels: core team 🌼
